const CONFIG={SUPABASE_URL:'https://waluhdgqhwjjwmflhrle.supabase.co',SUPABASE_ANON_KEY:'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdWJhc2UiLCJyZWYiOiJ3YWx1aGRncWh3amp3bWZsaHJsZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzg3NjE4ODYwLCJleHAiOjIxMDMxOTQ4NjB9.-UugGE05V70Ecw__UdIZpWJr2mDYmLfV7mh_lR-U9Mw'};
const Auth={token:null,load(){try{this.token=JSON.parse(localStorage.getItem('baekeok_auth'))?.access_token||null}catch(_){this.token=null}return this.token}};
async function rpc(fn,args={}){const r=await fetch(`${CONFIG.SUPABASE_URL}/rest/v1/rpc/${fn}`,{method:'POST',headers:{apikey:CONFIG.SUPABASE_ANON_KEY,Authorization:`Bearer ${Auth.token||CONFIG.SUPABASE_ANON_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(args)});const t=await r.text();if(!r.ok)throw new Error(t||`HTTP ${r.status}`);return t?JSON.parse(t):null}
const el=id=>document.getElementById(id),p2=n=>String(n).padStart(2,'0');
function parseWall(v){if(v instanceof Date)return v;const s=String(v||'').trim();const m=s.match(/^(\d{4})-(\d{2})-(\d{2})[ T](\d{2}):(\d{2})(?::(\d{2}))?/);return m?new Date(+m[1],+m[2]-1,+m[3],+m[4],+m[5],+(m[6]||0)):new Date(NaN)}
function dayKey(d){return `${d.getFullYear()}-${p2(d.getMonth()+1)}-${p2(d.getDate())}`}
function hm(d){return d&&!isNaN(d)?`${p2(d.getHours())}:${p2(d.getMinutes())}`:'—'}
function dur(sec){if(sec==null||!isFinite(sec))return '—';const m=Math.max(0,Math.floor(sec/60)),h=Math.floor(m/60),mm=m%60;return h?`${h}시간 ${mm}분`:`${mm}분`}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function applyCorrections(events,corrections){const latest=new Map(),added=[];for(const c of corrections||[]){if(c.action==='ADD'){added.push(c);continue}if(c.event_id==null)continue;const prev=latest.get(String(c.event_id));const a=String(c.created_at||'')+String(c.id||''),b=prev?String(prev.created_at||'')+String(prev.id||''):'';if(!prev||a>b)latest.set(String(c.event_id),c)}const out=[];for(const e of events||[]){const c=latest.get(String(e.id));if(c?.action==='VOID')continue;out.push({...e,event_at:c?.new_event_at||e.event_at,event_type:c?.new_event_type||e.event_type,corrected:!!c})}for(const c of added){out.push({id:`add_${c.id}`,employee_id:c.employee_id,event_type:c.new_event_type,event_at:c.new_event_at,corrected:true,addedByAdmin:true})}return out}
function pairEvents(events){const by=new Map();for(const e of events||[]){if(!by.has(Number(e.employee_id)))by.set(Number(e.employee_id),[]);by.get(Number(e.employee_id)).push(e)}const sessions=[];for(const [employeeId,rows] of by){rows.sort((a,b)=>parseWall(a.event_at)-parseWall(b.event_at)||String(a.id).localeCompare(String(b.id)));let open=null;for(const e of rows){const d=parseWall(e.event_at);if(isNaN(d))continue;if(e.event_type==='IN'){if(open)sessions.push({employee_id:employeeId,status:'INCOMPLETE',in:open.d,out:null,inId:open.e.id,corrected:!!open.e.corrected});open={d,e}}else if(e.event_type==='OUT'){if(open){sessions.push({employee_id:employeeId,status:'COMPLETE',in:open.d,out:d,inId:open.e.id,outId:e.id,sec:Math.max(0,(d-open.d)/1000),corrected:!!open.e.corrected||!!e.corrected});open=null}else sessions.push({employee_id:employeeId,status:'ORPHAN_OUT',in:null,out:d,outId:e.id,corrected:!!e.corrected})}}if(open)sessions.push({employee_id:employeeId,status:'WORKING',in:open.d,out:null,inId:open.e.id,corrected:!!open.e.corrected})}return sessions.sort((a,b)=>(a.in||a.out)-(b.in||b.out))}
function monthShift(ym,delta){const [y,m]=ym.split('-').map(Number),d=new Date(y,m-1+delta,1);return `${d.getFullYear()}-${p2(d.getMonth()+1)}`}
function addDays(iso,n){const [y,m,d]=iso.split('-').map(Number),x=new Date(y,m-1,d+n);return dayKey(x)}
function monthBounds(ym){const [y,m]=ym.split('-').map(Number);const first=`${y}-${p2(m)}-01`,next=monthShift(ym,1)+'-01';return {first,next}}
function kstToday(){return new Date(new Date().toLocaleString('en-US',{timeZone:'Asia/Seoul'}))}
const S={ym:'',employees:[],sessions:[],selectedDay:null};
function sessionAnchor(s){return s.in||s.out}
function sessionsForDay(day){return S.sessions.filter(s=>{const a=sessionAnchor(s);return a&&dayKey(a)===day})}
function isIssue(s,day){if(s.status==='INCOMPLETE'||s.status==='ORPHAN_OUT')return true;if(s.status==='WORKING'&&day!==dayKey(kstToday()))return true;if(s.status==='COMPLETE'&&s.sec>16*3600)return true;return false}
async function loadMonth(){const app=el('app');app.innerHTML='<div class="loading">실근무 기록 불러오는 중…</div>';const {first,next}=monthBounds(S.ym);el('monthLabel').textContent=S.ym.replace('-','년 ')+'월';try{const [employees,data]=await Promise.all([rpc('admin_list_employees'),rpc('admin_events_with_corrections',{p_from:addDays(first,-7)+'T00:00:00',p_to:addDays(next,7)+'T00:00:00'})]);S.employees=(employees||[]).filter(e=>e.is_active!==false&&e.active!==false).sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'ko-KR'));S.sessions=pairEvents(applyCorrections(data?.events||[],data?.corrections||[]));renderMonth()}catch(e){console.error('[actual-attendance]',e);if(String(e.message).includes('401')||String(e.message).includes('JWT')||String(e.message).includes('NOT_AUTHORIZED')){location.href='index.html#admin';return}app.innerHTML=`<div class="empty">실근무 현황을 불러오지 못했습니다.<br><button id="retry">다시 시도</button></div>`;el('retry').onclick=loadMonth}}
function renderMonth(){S.selectedDay=null;const [y,m]=S.ym.split('-').map(Number),days=new Date(y,m,0).getDate(),offset=new Date(y,m-1,1).getDay(),today=dayKey(kstToday());let html='<div class="weekhead"><div>일</div><div>월</div><div>화</div><div>수</div><div>목</div><div>금</div><div>토</div></div><div class="calendar">';for(let i=0;i<offset;i++)html+='<div class="day blank"></div>';for(let d=1;d<=days;d++){const day=`${S.ym}-${p2(d)}`,ss=sessionsForDay(day),issue=ss.some(s=>isIssue(s,day));const lines=ss.slice(0,3).map(s=>{const e=S.employees.find(x=>Number(x.id)===Number(s.employee_id)),name=escapeHtml(e?.name||`#${s.employee_id}`),range=s.status==='WORKING'?`${hm(s.in)}–진행중`:s.status==='ORPHAN_OUT'?`?–${hm(s.out)}`:`${hm(s.in)}–${hm(s.out)}`;return `<div class="line"><b>${name}</b> ${range}</div>`}).join('');html+=`<button class="day${day===today?' today':''}${issue?' issue':''}" data-day="${day}"><span class="num">${d}</span><div class="lines">${lines}${ss.length>3?`<div class="more">+${ss.length-3}건</div>`:''}</div></button>`}html+='</div><div class="legend"><span><i class="dot"></i>실제 근무</span><span><i class="dot warn"></i>확인 필요</span><span>날짜를 누르면 일별 타임라인</span></div>';el('app').innerHTML=html;document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>renderDay(b.dataset.day))}
function toAxisHour(d,day){const [y,m,da]=day.split('-').map(Number),base=new Date(y,m-1,da,0,0,0);return (d-base)/3600000}
function renderDay(day){S.selectedDay=day;const ss=sessionsForDay(day),byEmp=new Map();for(const s of ss){if(!byEmp.has(s.employee_id))byEmp.set(s.employee_id,[]);byEmp.get(s.employee_id).push(s)}const entries=[...byEmp.entries()].sort((a,b)=>{const ea=S.employees.find(x=>Number(x.id)===Number(a[0])),eb=S.employees.find(x=>Number(x.id)===Number(b[0]));return String(ea?.name||'').localeCompare(String(eb?.name||''),'ko-KR')});const labels=[7,10,13,16,19,22,25].map(h=>`<span>${h}:00</span>`).join('');let rows='';for(const [empId,list] of entries){const emp=S.employees.find(x=>Number(x.id)===Number(empId));let bars='';for(const s of list){const start=s.in||s.out,end=s.out||(day===dayKey(kstToday())?kstToday():new Date(...day.split('-').map((v,i)=>i===1?+v-1:+v),1,0,0));let a=toAxisHour(start,day),b=s.out?toAxisHour(end,day):(day===dayKey(kstToday())?toAxisHour(end,day):25);if(s.status==='ORPHAN_OUT')a=Math.max(7,b-.25);const left=Math.max(0,Math.min(100,(a-7)/18*100)),right=Math.max(left+.5,Math.min(100,(b-7)/18*100)),width=Math.max(.6,right-left),issue=isIssue(s,day);bars+=`<div class="bar${s.status==='WORKING'?' open':''}${issue?' issue':''}${s.corrected?' corrected':''}" style="left:${left}%;width:${width}%"><span class="bar-label">${s.status==='WORKING'?hm(s.in)+'–진행':s.status==='ORPHAN_OUT'?'퇴근 '+hm(s.out):hm(s.in)+'–'+hm(s.out)}</span></div>`}rows+=`<div class="person-row"><div class="person">${escapeHtml(emp?.name||`#${empId}`)}</div><div class="track">${bars}</div></div>`}let detail='';for(const s of ss){const emp=S.employees.find(x=>Number(x.id)===Number(s.employee_id)),issue=isIssue(s,day),label=s.status==='COMPLETE'?`${hm(s.in)}–${hm(s.out)} · ${dur(s.sec)}`:s.status==='WORKING'?`${hm(s.in)}–진행 중`:s.status==='INCOMPLETE'?`${hm(s.in)}–퇴근 누락`:`출근 누락–${hm(s.out)}`;detail+=`<div class="session"><div><b>${escapeHtml(emp?.name||'')}</b><div class="meta">${label}</div></div><div>${s.corrected?'<span class="pill">정정</span> ':''}${issue?'<span class="pill warn">확인 필요</span>':''}</div></div>`}el('app').innerHTML=`<section class="dayview"><div class="dayhead"><button id="backMonth">‹ 월간</button><div class="date">${day}</div><button id="todayBtn">오늘</button></div><div class="axis-wrap"><div class="axis"><div class="axis-labels">${labels}</div>${rows||'<div class="empty">이 날의 실제 출퇴근 기록이 없습니다.</div>'}</div></div><div class="sessions">${detail}</div></section>`;el('backMonth').onclick=renderMonth;el('todayBtn').onclick=()=>{const t=dayKey(kstToday()),ym=t.slice(0,7);if(ym!==S.ym){S.ym=ym;loadMonth().then(()=>renderDay(t))}else renderDay(t)}}
function init(){Auth.load();if(!Auth.token){location.href='index.html#admin';return}const t=kstToday();S.ym=`${t.getFullYear()}-${p2(t.getMonth()+1)}`;el('back').onclick=()=>location.href='index.html#admin';el('prevMonth').onclick=()=>{S.ym=monthShift(S.ym,-1);loadMonth()};el('nextMonth').onclick=()=>{S.ym=monthShift(S.ym,1);loadMonth()};el('monthLabel').onclick=()=>{const t=kstToday();S.ym=`${t.getFullYear()}-${p2(t.getMonth()+1)}`;loadMonth()};loadMonth()}
init();