function render(){const emp=currentEmp();if(!emp){document.getElementById("app").innerHTML='<div class="card">활성 직원이 없습니다.</div>';return}const sum=summary(emp.id),weeks=weekRows(S.ym);if(S.week>=weeks.length)S.week=weeks.length-1;const currentWeek=weeks[S.week]||[];const range=currentWeek.filter(Boolean);const rangeText=range.length?`${range[0].slice(5).replace('-','/')} – ${range.at(-1).slice(5).replace('-','/')}`:"";const empOpts=S.emps.map(e=>`<option value="${e.id}" ${Number(e.id)===Number(S.empId)?'selected':''}>${e.name}</option>`).join("");const weekdays=['일','월','화','수','목','금','토'];
const cell=d=>{if(!d)return '<div class="daycell outmonth"></div>';const r=effective(emp.id,d),k=rowKey(emp.id,d);return `<button class="daycell ${cellClass(r)} ${S.selected.has(d)?'selected':''} ${S.draft.has(k)?'dirty':''}" data-date="${d}"><div class="d">${Number(d.slice(8))} ${weekdays[weekday(d)]}</div><div class="s">${cellLabel(r)}</div></button>`};
const allGrid=weeks.flat().map(cell).join("");const weekGrid=currentWeek.map(cell).join("");
document.getElementById("app").innerHTML=`
<div class="card"><div class="label">직원</div><div class="empbar"><select id="empSel">${empOpts}</select></div><div class="summary"><div class="sum"><b>${sum.work}</b><span>WORK</span></div><div class="sum"><b>${sum.off}</b><span>OFF</span></div><div class="sum"><b>${sum.none}</b><span>미등록</span></div><div class="sum"><b>${fmtMin(sum.min)}</b><span>예정 합계</span></div></div></div>
<div class="card mobile-week"><div class="weeknav"><button class="btn" id="prevWeek">‹</button><div class="range">${rangeText}</div><button class="btn" id="nextWeek">›</button></div><div class="weekstrip">${weekGrid}</div></div>
<div class="card desktop-month"><div class="label">${S.ym} 전체 · 날짜를 여러 개 선택할 수 있습니다.</div><div class="desktop-grid">${allGrid}</div></div>
<div class="quick-area">
<div class="card"><div class="label">선택 날짜 일괄 적용</div><div class="quick-grid"><select id="mode"><option value="WORK" ${S.mode==='WORK'?'selected':''}>WORK</option><option value="OFF" ${S.mode==='OFF'?'selected':''}>OFF</option><option value="DELETE" ${S.mode==='DELETE'?'selected':''}>미등록 / 등록취소</option></select><button class="btn" id="clearSelection">선택 해제 (${S.selected.size})</button></div><div class="time-row" id="timeRow" style="${S.mode==='WORK'?'':'display:none'}"><input id="start" type="time" value="${S.start}"><span>~</span><input id="end" type="time" value="${S.end}"></div><div class="notice warn" id="pastWarn" style="${hasPastSelection()?'margin-top:8px':'display:none'}">실제 근태 기록이 있을 수 있는 과거 날짜입니다. 일정 변경은 근태 기록을 변경하지 않습니다.</div><div class="actions"><button class="btn primary" id="applySelected">선택 ${S.selected.size}일에 적용</button></div></div>
<div class="card"><div class="label">요일 반복 빠른 입력</div><div class="weekdays">${weekdays.map((w,i)=>`<button class="wd ${S.weekdays.has(i)?'on':''}" data-wd="${i}">${w}</button>`).join('')}</div><div class="notice" style="margin-top:8px">현재 선택한 직원의 ${S.ym} 전체에서 선택 요일에 위 WORK/OFF/미등록 설정을 draft로 적용합니다.</div><div class="actions"><button class="btn primary" id="applyWeekdays">선택 요일에 적용</button></div></div>
</div>
<div class="card"><div class="copyline"><div class="desc"><b>전월 스케줄 복사</b><br>직원별로 전월의 같은 요일·같은 순번(예: 둘째 월요일)을 현재월에 복사합니다. 현재월에 이미 저장된 일정 또는 이미 편집 중인 날짜는 건드리지 않습니다. 결과는 draft에만 추가됩니다.</div><button class="btn" id="copyPrev">${prevYM(S.ym)} 복사</button></div></div>
<div class="card notice">WorkSchedule은 계획 데이터입니다. 월간 편집은 출퇴근 기록, correction, 급여, 주휴/결근 판정을 생성하거나 변경하지 않습니다.</div>`;
bind();updateSavebar()}
function bind(){document.getElementById("empSel").onchange=e=>{S.empId=Number(e.target.value);S.selected.clear();render()};document.querySelectorAll(".daycell[data-date]").forEach(b=>b.onclick=()=>{const d=b.dataset.date;S.selected.has(d)?S.selected.delete(d):S.selected.add(d);render()});const pw=document.getElementById("prevWeek"),nw=document.getElementById("nextWeek");if(pw)pw.onclick=()=>{S.week=Math.max(0,S.week-1);S.selected.clear();render()};if(nw)nw.onclick=()=>{S.week=Math.min(weekRows(S.ym).length-1,S.week+1);S.selected.clear();render()};document.getElementById("mode").onchange=e=>{S.mode=e.target.value;if(S.mode==='WORK')ensureWorkDefault();render()};const st=document.getElementById("start"),en=document.getElementById("end");if(st)st.onchange=e=>S.start=e.target.value;if(en)en.onchange=e=>S.end=e.target.value;document.getElementById("clearSelection").onclick=()=>{S.selected.clear();render()};document.getElementById("applySelected").onclick=()=>applyDates([...S.selected]);document.querySelectorAll(".wd").forEach(b=>b.onclick=()=>{const i=Number(b.dataset.wd);S.weekdays.has(i)?S.weekdays.delete(i):S.weekdays.add(i);render()});document.getElementById("applyWeekdays").onclick=()=>applyDates(monthDates(S.ym).filter(d=>S.weekdays.has(weekday(d))));document.getElementById("copyPrev").onclick=copyPreviousMonth}
function applyDates(dates){if(!dates.length){toast("적용할 날짜를 선택하세요.",true);return}if(S.mode==='WORK'){if(!S.start||!S.end){toast("WORK 시작/종료 시각을 입력하세요.",true);return}if(S.start===S.end){toast("시작과 종료 시각은 같을 수 없습니다.",true);return}}const emp=currentEmp();for(const d of dates){if(S.mode==='DELETE')setDraft(emp.id,d,null);else if(S.mode==='OFF')setDraft(emp.id,d,{employee_id:emp.id,work_date:d,status:'OFF'});else setDraft(emp.id,d,{employee_id:emp.id,work_date:d,status:'WORK',planned_start:S.start,planned_end:S.end})}S.selected.clear();render()}
async function copyPreviousMonth(){const prev=prevYM(S.ym),[pf,pt]=monthRange(prev);let rows;try{rows=await BE.scheduleList(pf,pt)}catch(e){toast("전월 일정을 불러오지 못했습니다.",true);return}const prevMap=new Map(rows.map(r=>[rowKey(r.employee_id,String(r.work_date).slice(0,10)),normRow(r)]));let n=0;for(const e of S.emps){for(const d of monthDates(S.ym)){const k=rowKey(e.id,d);if(S.original.has(k)||S.draft.has(k))continue;const src=nthWeekdaySource(d,prev);if(!src)continue;const r=prevMap.get(rowKey(e.id,src));if(!r)continue;setDraft(e.id,d,{...r,employee_id:Number(e.id),work_date:d});if(S.draft.has(k))n++}}toast(n?`전월 패턴 ${n}건을 draft에 추가했습니다.`:"복사할 미등록 일정이 없습니다.");render()}
function draftPayload(){const out=[];for(const [k,r] of S.draft){const [employee_id,work_date]=k.split('|');if(r)out.push({op:'SET',employee_id:Number(employee_id),work_date,status:r.status,planned_start:r.planned_start,planned_end:r.planned_end,memo:r.memo||null});else out.push({op:'DELETE',employee_id:Number(employee_id),work_date})}return out}
async function saveDraft(){if(S.busy||!S.draft.size)return;S.busy=true;document.getElementById("saveDraft").disabled=true;const payload=draftPayload();try{const r=await BE.scheduleBatch(payload);if(!r||r.ok===false)throw new Error((r&&r.error)||'SAVE_FAILED');toast(`${payload.length}건 저장했습니다.`);await loadMonth(true)}catch(e){const raw=String(e&&e.message||e||'');const network=(e&&e.name==='TypeError')||/failed to fetch|load failed|networkerror|network request failed|fetch/i.test(raw);toast(network?"저장하지 못했습니다. 입력한 변경사항은 유지됩니다. 네트워크 연결을 확인하고 다시 시도하세요.":`저장하지 못했습니다. 입력한 변경사항은 유지됩니다. ${raw}`,true);S.busy=false;render();return}S.busy=false}
function cancelDraft(){if(!S.draft.size)return;if(!confirm(`저장하지 않은 변경 ${S.draft.size}건을 모두 취소할까요?`))return;S.draft.clear();S.selected.clear();render()}
async function loadMonth(afterSave=false){const [f,t]=monthRange(S.ym);document.getElementById("app").innerHTML='<div class="loading">불러오는 중…</div>';try{const [emps,rows]=await Promise.all([BE.allEmployees(),BE.scheduleList(f,t)]);S.emps=activeEmps(emps);if(!S.emps.some(e=>Number(e.id)===Number(S.empId)))S.empId=S.emps[0]?.id??null;S.original=new Map(rows.map(r=>[rowKey(r.employee_id,String(r.work_date).slice(0,10)),normRow(r)]));if(afterSave)S.draft.clear();S.selected.clear();S.week=Math.min(Math.floor((kstNow().getDate()+localDate(`${S.ym}-01`).getDay()-1)/7),weekRows(S.ym).length-1);render()}catch(e){document.getElementById("app").innerHTML=`<div class="card"><b>불러오기 실패</b><div class="notice" style="margin-top:8px">${String(e.message||e)}</div><div class="actions"><button class="btn primary" id="retry">다시 시도</button></div></div>`;document.getElementById("retry").onclick=()=>loadMonth(false)}}
async function init(){Auth.load();if(!Auth.token){location.href='index.html#admin';return}let ok=false;try{ok=await BE.isAdmin()}catch(_){}if(!ok){document.getElementById("app").innerHTML='<div class="card">관리자 권한을 확인할 수 없습니다. <a href="index.html#admin">관리자로 돌아가기</a></div>';return}S.ym=monthNow();document.getElementById("month").value=S.ym;await loadMonth(false)}
document.getElementById("back").onclick=()=>location.href='index.html#admin';document.getElementById("prevMonth").onclick=()=>changeMonth(prevYM(S.ym));document.getElementById("nextMonth").onclick=()=>changeMonth(nextYM(S.ym));document.getElementById("thisMonth").onclick=()=>changeMonth(monthNow());document.getElementById("month").onchange=e=>changeMonth(e.target.value);document.getElementById("cancelDraft").onclick=cancelDraft;document.getElementById("saveDraft").onclick=saveDraft;
function changeMonth(ym){if(!ym||ym===S.ym)return;if(S.draft.size&&!confirm(`저장하지 않은 변경 ${S.draft.size}건이 있습니다. 취소하고 다른 달로 이동할까요?`)){document.getElementById("month").value=S.ym;return}S.draft.clear();S.selected.clear();S.ym=ym;document.getElementById("month").value=ym;loadMonth(false)}
init();
