/* 매장운영 V2 — 매출/매입/재고/BOM/대사 공통 기반. 실제 원천 어댑터만 추후 매장 자료로 매핑. */
(function(){
const S={tab:"dashboard",trend:"1m"},won=n=>Number(n||0).toLocaleString("ko-KR")+"원",num=n=>Number(n||0).toLocaleString("ko-KR"),esc=v=>window.safeHtml?window.safeHtml(v):String(v??"");
function range(){const d=window.kstNow?window.kstNow():new Date(),p=n=>String(n).padStart(2,"0");return [`${d.getFullYear()}-${p(d.getMonth()+1)}-01`,`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(new Date(d.getFullYear(),d.getMonth()+1,0).getDate())}`]}
function empty(t,s=""){return `<div class="ops-empty"><b>${esc(t)}</b>${s?`<small>${esc(s)}</small>`:""}</div>`}
function shell(){const[f,t]=range();view.innerHTML=`<div class="ops-head"><div><h2>매장운영</h2><p>매출 · 매입 · 재고 · 원가 흐름을 한 곳에서 관리합니다.</p></div></div><div class="ops-tabs">
${[["dashboard","리포트"],["inquiry","데이터 조회"],["collect","데이터 수집"],["upload","파일 업로드"],["inventory","재고"],["recipe","레시피"],["recon","대사"]].map(([k,n],i)=>`<button class="ops-tab ${i?"":"on"}" data-ops="${k}">${n}</button>`).join("")}</div>
<div class="ops-demo"><span><b>예시 데이터</b> 공개 카페 데이터/레시피를 참고한 UI 검증용이며 실제 매장 실적이 아닙니다.</span><div><button class="btn btn-secondary btn-sm" id="opsDemoSeed">예시 채우기</button><button class="btn btn-tertiary btn-sm" id="opsDemoClear">예시 삭제</button></div></div><div class="ops-filter"><div><label>시작일</label><input id="opsFrom" type="date" value="${f}"></div><div><label>종료일</label><input id="opsTo" type="date" value="${t}"></div><button class="btn btn-primary" id="opsRefresh">조회</button></div><div id="opsBody"></div>`;
document.querySelectorAll(".ops-tab").forEach(b=>b.onclick=()=>{S.tab=b.dataset.ops;document.querySelectorAll(".ops-tab").forEach(x=>x.classList.toggle("on",x===b));draw()});opsRefresh.onclick=draw;opsDemoSeed.onclick=async()=>{opsDemoSeed.disabled=true;try{await BE.seedOperationsDemo();await draw()}catch(e){alert(e.message)}finally{opsDemoSeed.disabled=false}};opsDemoClear.onclick=async()=>{if(!confirm("예시 데이터만 삭제할까요?"))return;await BE.clearOperationsDemo();await draw()};draw()}
async function draw(){const body=document.getElementById("opsBody");if(!body)return;let trendData=null;body.innerHTML=empty("불러오는 중…");try{const f=opsFrom.value,t=opsTo.value;if(!f||!t||t<f)throw Error("조회 기간을 확인하세요.");
if(S.tab==="dashboard"){const[s,a,tr]=await Promise.all([BE.operationsSummary(f,t),BE.operationsAnalytics(f,t),BE.operationsTrend(S.trend)]);trendData=tr;const daily=a.daily||[],channels=a.by_channel||[];body.innerHTML=`<div class="ops-kpis"><div class="ops-kpi primary"><span>매출</span><b>${won(s.sales)}</b></div><div class="ops-kpi"><span>매입</span><b>${won(s.purchases)}</b></div><div class="ops-kpi"><span>재고 부족</span><b>${num(a.low_stock)}개</b></div><div class="ops-kpi"><span>미해결 대사</span><b>${num(a.open_reconciliation)}건</b></div></div>
<div class="ops-card ops-trend-card"><div class="ops-card-head"><div><b>매출 · 매입 추이</b><small>선택 기간의 총액 변화</small></div></div><div class="ops-range"><button data-range="1h" ${S.trend==="1h"?"class=\"on\"":""}>1시간</button><button data-range="24h" ${S.trend==="24h"?"class=\"on\"":""}>24시간</button><button data-range="7d" ${S.trend==="7d"?"class=\"on\"":""}>1주일</button><button data-range="1m" ${S.trend==="1m"?"class=\"on\"":""}>1달</button><button data-range="6m" ${S.trend==="6m"?"class=\"on\"":""}>6달</button><button data-range="1y" ${S.trend==="1y"?"class=\"on\"":""}>1년</button></div><div class="ops-chart" id="opsTotalChart"></div></div><div class="ops-card ops-trend-card"><div class="ops-card-head"><div><b>메뉴별 매출 추이</b><small>매출 상위 메뉴 최대 8개</small></div></div><div class="ops-chart ops-menu-chart" id="opsMenuChart"></div></div><div class="ops-card"><div class="ops-card-head"><b>채널별 매출</b><span class="ops-meta">${num(s.transaction_count)}건</span></div>${channels.length?channels.map(x=>`<div class="ops-row"><div class="ops-row-main"><b>${esc(x.channel)}</b><small>${num(x.transactions)}건</small></div><strong>${won(x.amount)}</strong></div>`).join(""):empty("매출 데이터 없음","원천 데이터를 연결하면 자동 집계됩니다.")}</div>
<div class="ops-card"><div class="ops-card-head"><b>일별 흐름</b></div>${daily.length?daily.slice(-14).map(x=>`<div class="ops-row"><div class="ops-row-main"><b>${esc(x.business_date)}</b><small>매입 ${won(x.purchases)}</small></div><strong>${won(x.sales)}</strong></div>`).join(""):empty("집계할 거래가 없습니다.")}</div>`}
else if(S.tab==="inquiry"){const [rows,chs]=await Promise.all([BE.operationsInquiry(f,t,null,null),BE.operationsChannels(f,t)]);const sales=rows.filter(x=>x.transaction_type==="SALE"),purchases=rows.filter(x=>x.transaction_type==="PURCHASE"),sum=(a,k)=>a.reduce((v,x)=>v+Number(x[k]||0),0);body.innerHTML=`<div class="ops-inquiry-filter"><select id="opsType"><option value="">구분 (전체)</option><option value="SALE">매출</option><option value="PURCHASE">매입</option><option value="REFUND">환불</option></select><select id="opsChannel"><option value="">채널 (전체)</option>${chs.map(x=>`<option>${esc(x.channel)}</option>`).join("")}</select></div><div class="ops-summary"><span>조회 결과 <b>${num(rows.length)}건</b></span><div><span>공급가액 <b>${won(sum(rows,"net_amount"))}</b></span><span>부가세 <b>${won(sum(rows,"vat_amount"))}</b></span><span class="total">합계 <b>${won(sum(rows,"total_amount"))}</b></span></div></div><div class="ops-table-wrap"><table class="ops-table"><thead><tr><th>일자</th><th>구분</th><th>채널</th><th>공급가액</th><th>부가세</th><th>합계</th><th>거래처/메뉴</th></tr></thead><tbody>${rows.length?rows.slice(0,100).map(x=>`<tr><td>${esc(x.business_date)}</td><td>${x.transaction_type==="SALE"?"매출":x.transaction_type==="PURCHASE"?"매입":esc(x.transaction_type)}</td><td>${esc(x.channel||"-")}</td><td>${won(x.net_amount)}</td><td>${won(x.vat_amount)}</td><td><b>${won(x.total_amount)}</b></td><td>${esc(x.counterparty||"-")}${x.is_demo?'<small class="ops-demo-mark">예시</small>':""}</td></tr>`).join(""):`<tr><td colspan="7">${empty("조회된 데이터가 없습니다.")}</td></tr>`}</tbody></table></div>`;opsType.onchange=async()=>{const rr=await BE.operationsInquiry(f,t,opsType.value||null,opsChannel.value||null);S.filtered=rr;drawInquiryRows(rr)};opsChannel.onchange=opsType.onchange}
else if(S.tab==="collect"){const rows=await BE.operationsImports();body.innerHTML=`<div class="ops-subhead"><b>데이터 수집</b><span>BizReport의 스크래핑 작업 흐름을 POS·배달·공급사 수집 큐로 확장했습니다.</span></div><div class="ops-source-grid">${[["KIS POS","매출·결제"],["배민","주문·정산"],["쿠팡이츠","주문·정산"],["땡겨요","주문·정산"],["온리원푸드넷","매입·입고"]].map(x=>`<div class="ops-source"><b>${x[0]}</b><small>${x[1]}</small><span class="ops-status">어댑터 준비</span></div>`).join("")}</div><div class="ops-card"><div class="ops-card-head"><b>수집 작업 이력</b><span class="ops-meta">${rows.length}건</span></div>${rows.length?rows.map(r=>`<div class="ops-row"><div class="ops-row-main"><b>${esc(r.source)}</b><small>${esc(r.file_name||"직접 수집")}</small></div><span class="ops-status ${r.status==="COMPLETED"?"ok":""}">${esc(r.status)}</span></div>`).join(""):empty("수집 작업 없음")}</div>`}
else if(S.tab==="upload"){const rows=await BE.operationsImports();body.innerHTML=`<div class="ops-subhead"><b>파일 업로드</b><span>BizReport의 카드 CSV 업로드 UX를 원천별 표준 업로드로 확장합니다.</span></div><div class="ops-upload-box"><label>데이터 원천<select disabled><option>CSV/XLSX — 실제 컬럼 매핑 준비 중</option></select></label><label>대상 파일<input type="file" accept=".csv,.xlsx,.xls" disabled></label><div class="ops-upload-actions"><button class="btn btn-secondary" disabled>표준서식 받기</button><button class="btn btn-primary" disabled>검증 후 업로드</button></div><small>실제 KIS/배민/공급사 파일을 받으면 컬럼 매핑을 확정한 뒤 활성화합니다. 임의 형식으로 운영 데이터를 변환하지 않습니다.</small></div><div class="ops-card"><b>업로드 대기열</b>${rows.length?rows.map(r=>`<div class="ops-row"><span>${esc(r.file_name||r.source)}</span><span class="ops-status">${esc(r.status)}</span></div>`).join(""):empty("업로드 기록 없음")}</div>`}
else if(S.tab==="inventory"){const rows=await BE.inventoryOverview();body.innerHTML=`<div class="ops-note">입고 + / 판매사용·폐기 − / 실사조정 ± 방식의 불변 재고원장입니다. 품목별 현재고와 재주문 기준을 계산합니다.</div>`+(rows.length?rows.map(r=>`<div class="ops-card ${r.low_stock?"ops-alert":""}"><div class="ops-card-head"><b class="ops-card-title">${esc(r.name)}</b><span class="ops-status ${r.low_stock?"warn":r.is_active?"ok":""}">${r.low_stock?"재고 부족":r.is_active?"사용중":"중지"}</span></div><div class="ops-stock"><strong>${num(r.on_hand)} ${esc(r.unit)}</strong><span>재고가치 ${won(r.inventory_value)}</span></div><div class="ops-meta">SKU ${esc(r.sku)}${r.reorder_level!=null?` · 재주문 기준 ${num(r.reorder_level)} ${esc(r.unit)}`:""}</div></div>`).join(""):empty("등록된 재고 품목이 없습니다.","품목 마스터는 실제 규격 확인 후 등록합니다."))}
else if(S.tab==="recipe"){const rows=await BE.recipeList();body.innerHTML=`<div class="ops-note">레시피는 덮어쓰지 않고 유효기간별 버전을 보존합니다. 판매수량 × BOM으로 이론 사용량을 계산할 수 있는 구조입니다.</div>`+(rows.length?rows.map(r=>`<div class="ops-card"><div class="ops-card-head"><b>${esc(r.menu_name)}</b><span class="ops-status">${esc(r.effective_from)}~${esc(r.effective_to||"현재")}</span></div>${(r.components||[]).map(c=>`<div class="ops-row"><span>${esc(c.item_name)}</span><strong>${num(c.quantity)} ${esc(c.unit)}</strong></div>`).join("")||empty("구성품 없음")}</div>`).join(""):empty("등록된 레시피가 없습니다.","실제 메뉴와 사용량을 받으면 버전형 BOM에 연결합니다."))}
else if(S.tab==="recon"){const rows=await BE.reconciliationIssues(f,t);body.innerHTML=`<div class="ops-note">POS ↔ 배달/결제, 매입 ↔ 입고 등 서로 다른 원천의 누락·금액차이·취소 불일치를 기록하는 대사 큐입니다.</div>`+(rows.length?rows.map(r=>`<div class="ops-card"><div class="ops-card-head"><b>${esc(r.issue_type)}</b><span class="ops-status ${r.status==="OPEN"?"warn":"ok"}">${esc(r.status)}</span></div><div class="ops-row"><div class="ops-row-main"><b>${esc(r.business_date)}</b><small>${esc(r.left_source||"-")} ↔ ${esc(r.right_source||"-")}</small></div><strong>${r.amount_difference==null?"-":won(r.amount_difference)}</strong></div></div>`).join(""):empty("대사 이상 없음","연결된 원천이 없으면 검사 대상도 없습니다."))}
else{body.innerHTML=empty("화면을 불러올 수 없습니다.")}
if(S.tab==="dashboard"){renderTrendCharts(trendData);document.querySelectorAll(".ops-range button").forEach(b=>b.onclick=async()=>{S.trend=b.dataset.range;document.querySelectorAll(".ops-range button").forEach(x=>x.classList.toggle("on",x===b));renderTrendCharts(await BE.operationsTrend(S.trend))})}}catch(e){body.innerHTML=empty("불러오기 실패",e.message)}}
function renderTrendCharts(tr){
 const totals=tr&&tr.totals||[],menus=tr&&tr.menus||[],names=tr&&tr.menu_names||[];
 const label=x=>{const d=new Date(x);if(S.trend==="1h")return String(d.getMinutes()).padStart(2,"0")+"분";if(S.trend==="24h")return String(d.getHours()).padStart(2,"0")+"시";if(S.trend==="1y")return (d.getMonth()+1)+"월";return (d.getMonth()+1)+"/"+d.getDate()};
 function chart(el,series,mode="bar"){if(!el)return;if(!series.length||!series[0].values.length){el.innerHTML=empty("이 기간에 표시할 데이터가 없습니다.","예시 데이터는 최근 30일 기준입니다. 1달을 선택하거나 예시 데이터를 다시 채워보세요.");return}
  const W=640,H=250,L=38,R=8,T=12,B=42,count=series[0].values.length,max=Math.max(1,...series.flatMap(s=>s.values.map(v=>Number(v.v||0)))),plotW=W-L-R,plotH=H-T-B,group=plotW/count,gap=Math.max(1,Math.min(4,group*.08)),barW=Math.max(1,(group-gap*2)/Math.max(1,series.length));
  const y=v=>T+plotH-(Number(v||0)/max)*plotH;
  const grid=[0,.25,.5,.75,1].map(k=>'<line x1="'+L+'" x2="'+(W-R)+'" y1="'+y(max*k)+'" y2="'+y(max*k)+'"/>').join("");
  const marks=mode==="line"?series.map((s,si)=>{const pts=s.values.map((v,i)=>(L+i*group+group/2).toFixed(1)+","+y(v.v).toFixed(1)).join(" ");const dots=s.values.map((v,i)=>{const val=Number(v.v||0),x=L+i*group+group/2,yy=y(val);return '<circle tabindex="0" role="button" data-series="'+esc(s.name)+'" data-label="'+esc(label(v.x))+'" data-value="'+val+'" class="s'+(si%8)+'" cx="'+x.toFixed(1)+'" cy="'+yy.toFixed(1)+'" r="5" class="s'+(si%8)+' ops-chart-point"/>''}).join("");return '<polyline class="s'+(si%8)+'" points="'+pts+'"/>'+dots}).join(""):series.map((s,si)=>s.values.map((v,i)=>{const val=Number(v.v||0),x=L+i*group+gap+si*barW,yy=y(val),hh=Math.max(0,T+plotH-yy);return '<rect tabindex="0" role="button" data-series="'+esc(s.name)+'" data-label="'+esc(label(v.x))+'" data-value="'+val+'" class="s'+(si%8)+'" x="'+x.toFixed(1)+'" y="'+yy.toFixed(1)+'" width="'+Math.max(1,barW-1).toFixed(1)+'" height="'+hh.toFixed(1)+'" rx="2"/>'}).join("")).join("");
  const step=Math.max(1,Math.ceil(count/6)),labs=series[0].values.map((v,i)=>i%step===0?'<text x="'+(L+i*group+group/2).toFixed(1)+'" y="'+(H-13)+'">'+label(v.x)+'</text>':"").join("");
  el.innerHTML='<div class="ops-chart-stage"><svg viewBox="0 0 '+W+' '+H+'" role="img">'+grid+marks+labs+'</svg><div class="ops-chart-tip" hidden></div></div><div class="ops-legend">'+series.map((s,i)=>'<span><i class="s'+(i%8)+'"></i>'+esc(s.name)+'</span>').join("")+'</div>';const tip=el.querySelector('.ops-chart-tip'),stage=el.querySelector('.ops-chart-stage');let selected=null;const show=(r)=>{selected=r;tip.innerHTML='<b>'+esc(r.dataset.series)+'</b><span>'+esc(r.dataset.label)+'</span><strong>'+won(r.dataset.value)+'</strong>';tip.hidden=false;const rb=r.getBoundingClientRect(),sb=stage.getBoundingClientRect();tip.style.left=Math.max(8,Math.min(sb.width-tip.offsetWidth-8,rb.left-sb.left+rb.width/2-tip.offsetWidth/2))+'px';tip.style.top=Math.max(8,rb.top-sb.top-tip.offsetHeight-8)+'px'},hide=()=>{selected=null;tip.hidden=true};el.querySelectorAll('[data-series]').forEach(r=>{r.addEventListener('pointerdown',e=>{show(r);if(e.pointerType!=='mouse')e.stopPropagation()},{passive:true});r.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse')show(r)});r.addEventListener('pointerleave',e=>{if(e.pointerType==='mouse'&&selected===r)hide()});r.addEventListener('focus',()=>show(r));r.addEventListener('click',e=>{e.stopPropagation();show(r)})});stage.addEventListener('pointerdown',e=>{if(!e.target.closest('[data-series]'))hide()},{passive:true})
 }
 chart(document.getElementById("opsTotalChart"),[{name:"총매출",values:totals.map(x=>({x:x.bucket,v:x.sales}))},{name:"총매입",values:totals.map(x=>({x:x.bucket,v:x.purchases}))}]);
 chart(document.getElementById("opsMenuChart"),names.map(n=>({name:n,values:totals.map(t=>({x:t.bucket,v:(menus.find(m=>m.bucket===t.bucket&&m.menu===n)||{}).amount||0}))})),"line");
}
function drawInquiryRows(rows){const tb=document.querySelector(".ops-table tbody");if(!tb)return;tb.innerHTML=rows.length?rows.slice(0,100).map(x=>`<tr><td>${esc(x.business_date)}</td><td>${x.transaction_type==="SALE"?"매출":x.transaction_type==="PURCHASE"?"매입":esc(x.transaction_type)}</td><td>${esc(x.channel||"-")}</td><td>${won(x.net_amount)}</td><td>${won(x.vat_amount)}</td><td><b>${won(x.total_amount)}</b></td><td>${esc(x.counterparty||"-")}${x.is_demo?'<small class="ops-demo-mark">예시</small>':""}</td></tr>`).join(""):`<tr><td colspan="7">${empty("조회된 데이터가 없습니다.")}</td></tr>`} window.renderOperations=shell})();
