/* 매장운영 V2 — 매출/매입/재고/BOM/대사 공통 기반. 실제 원천 어댑터만 추후 매장 자료로 매핑. */
(function(){
const S={tab:"dashboard",trend:"1m"},won=n=>Number(n||0).toLocaleString("ko-KR")+"원",num=n=>Number(n||0).toLocaleString("ko-KR"),esc=v=>window.safeHtml?window.safeHtml(v):String(v??"");
function range(){const d=window.kstNow?window.kstNow():new Date(),p=n=>String(n).padStart(2,"0");return [`${d.getFullYear()}-${p(d.getMonth()+1)}-01`,`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(new Date(d.getFullYear(),d.getMonth()+1,0).getDate())}`]}
function empty(t,s=""){return `<div class="ops-empty"><b>${esc(t)}</b>${s?`<small>${esc(s)}</small>`:""}</div>`}
function shell(tab){
 S.tab=tab||S.tab;
 const[f,t]=range(),titles={dashboard:["리포트","매출·매입·재고·원가 흐름을 요약합니다."],inquiry:["매출·매입","거래 데이터를 조회하고 원천 데이터를 관리합니다."],inventory:["재고","카테고리별 현재고와 발주 필요량을 확인합니다."],recipe:["레시피","메뉴별 표준 레시피와 원가 구조를 관리합니다."]},meta=titles[S.tab]||["매장운영",""];
 const salesActions=S.tab==="inquiry"?'<div class="ops-head-actions"><button class="btn btn-secondary btn-sm" id="opsCollectOpen">데이터 수집</button><button class="btn btn-secondary btn-sm" id="opsUploadOpen">파일 업로드</button></div>':"";
 const filter=(S.tab==="dashboard"||S.tab==="inquiry")?'<div class="ops-filter"><div><label>시작일</label><input id="opsFrom" type="date" value="'+f+'"></div><div><label>종료일</label><input id="opsTo" type="date" value="'+t+'"></div><button class="btn btn-primary" id="opsRefresh">조회</button></div>':"";
 view.innerHTML='<div class="ops-head"><div><h2>'+meta[0]+'</h2><p>'+meta[1]+'</p></div>'+salesActions+'</div>'+filter+'<div id="opsBody"></div>';
 if(document.getElementById("opsRefresh"))opsRefresh.onclick=draw;
 if(document.getElementById("opsCollectOpen"))opsCollectOpen.onclick=()=>openOpsModal("collect");
 if(document.getElementById("opsUploadOpen"))opsUploadOpen.onclick=()=>openOpsModal("upload");
 draw()
}
async function openOpsModal(kind){
 let rows=[];try{rows=await BE.operationsImports()}catch(_){}
 const collect='<div class="ops-subhead"><b>데이터 수집</b><span>POS·배달·공급사 데이터를 연결하고 수집 상태를 확인합니다.</span></div><div class="ops-source-grid">'+[["KIS POS","매출·결제"],["배민","주문·정산"],["쿠팡이츠","주문·정산"],["땡겨요","주문·정산"],["온리원푸드넷","매입·입고"]].map(x=>'<div class="ops-source"><b>'+x[0]+'</b><small>'+x[1]+'</small><span class="ops-status">어댑터 준비</span></div>').join("")+'</div><div class="ops-card"><div class="ops-card-head"><b>수집 작업 이력</b><span class="ops-meta">'+rows.length+'건</span></div>'+(rows.length?rows.map(r=>'<div class="ops-row"><div class="ops-row-main"><b>'+esc(r.source)+'</b><small>'+esc(r.file_name||"직접 수집")+'</small></div><span class="ops-status '+(r.status==="COMPLETED"?"ok":"")+'">'+esc(r.status)+'</span></div>').join(""):empty("등록된 수집 작업이 없습니다."))+'</div>';
 const upload='<div class="ops-subhead"><b>파일 업로드</b><span>매출·매입 원천 파일을 표준 형식으로 검증해 등록합니다.</span></div><div class="ops-upload-box"><label>데이터 원천<select disabled><option>CSV/XLSX — 실제 컬럼 매핑 준비 중</option></select></label><label>대상 파일<input type="file" accept=".csv,.xlsx,.xls" disabled></label><div class="ops-upload-actions"><button class="btn btn-secondary" disabled>표준서식 받기</button><button class="btn btn-primary" disabled>검증 후 업로드</button></div></div>';
 const wrap=document.createElement("div");wrap.className="ops-modal";wrap.innerHTML='<div class="ops-modal-sheet"><div class="ops-modal-head"><b>'+(kind==="collect"?"데이터 수집":"파일 업로드")+'</b><button type="button" aria-label="닫기">×</button></div><div class="ops-modal-body">'+(kind==="collect"?collect:upload)+'</div></div>';document.body.appendChild(wrap);wrap.querySelector("button").onclick=()=>wrap.remove();wrap.onclick=e=>{if(e.target===wrap)wrap.remove()}
}
async function draw(){const body=document.getElementById("opsBody");if(!body)return;let trendData=null;body.innerHTML=empty("불러오는 중…");try{const rr=range(),f=document.getElementById("opsFrom")?.value||rr[0],t=document.getElementById("opsTo")?.value||rr[1];if(!f||!t||t<f)throw Error("조회 기간을 확인하세요.");
if(S.tab==="dashboard"){const[s,a,tr]=await Promise.all([BE.operationsSummary(f,t),BE.operationsAnalytics(f,t),BE.operationsTrend(S.trend)]);trendData=tr;const daily=a.daily||[],channels=a.by_channel||[];body.innerHTML=`<div class="ops-kpis"><div class="ops-kpi primary"><span>매출</span><b>${won(s.sales)}</b></div><div class="ops-kpi"><span>매입</span><b>${won(s.purchases)}</b></div><div class="ops-kpi"><span>재고 부족</span><b>${num(a.low_stock)}개</b></div><div class="ops-kpi"><span>미해결 대사</span><b>${num(a.open_reconciliation)}건</b></div></div>
<div class="ops-card ops-trend-card"><div class="ops-card-head"><div><b>매출 · 매입 추이</b><small>선택 기간의 총액 변화</small></div></div><div class="ops-range"><button data-range="1h" ${S.trend==="1h"?"class=\"on\"":""}>1시간</button><button data-range="24h" ${S.trend==="24h"?"class=\"on\"":""}>24시간</button><button data-range="7d" ${S.trend==="7d"?"class=\"on\"":""}>1주일</button><button data-range="1m" ${S.trend==="1m"?"class=\"on\"":""}>1달</button><button data-range="6m" ${S.trend==="6m"?"class=\"on\"":""}>6달</button><button data-range="1y" ${S.trend==="1y"?"class=\"on\"":""}>1년</button></div><div class="ops-chart" id="opsTotalChart"></div></div><div class="ops-card ops-trend-card"><div class="ops-card-head"><div><b>메뉴별 매출 추이</b><small>매출 상위 메뉴 최대 8개</small></div></div><div class="ops-chart ops-menu-chart" id="opsMenuChart"></div></div><div class="ops-card"><div class="ops-card-head"><b>채널별 매출</b><span class="ops-meta">${num(s.transaction_count)}건</span></div>${channels.length?channels.map(x=>`<div class="ops-row"><div class="ops-row-main"><b>${esc(x.channel)}</b><small>${num(x.transactions)}건</small></div><strong>${won(x.amount)}</strong></div>`).join(""):empty("등록된 매출 데이터가 없습니다.","원천 데이터를 연결하면 자동 집계됩니다.")}</div>
<div class="ops-card"><div class="ops-card-head"><b>일별 흐름</b></div>${daily.length?daily.slice(-14).map(x=>`<div class="ops-row"><div class="ops-row-main"><b>${esc(x.business_date)}</b><small>매입 ${won(x.purchases)}</small></div><strong>${won(x.sales)}</strong></div>`).join(""):empty("집계할 거래가 없습니다.")}</div>`}
else if(S.tab==="inquiry"){const [rows,chs]=await Promise.all([BE.operationsInquiry(f,t,null,null),BE.operationsChannels(f,t)]);const sales=rows.filter(x=>x.transaction_type==="SALE"),purchases=rows.filter(x=>x.transaction_type==="PURCHASE"),sum=(a,k)=>a.reduce((v,x)=>v+Number(x[k]||0),0);body.innerHTML=`<div class="ops-inquiry-filter"><select id="opsType"><option value="">구분 (전체)</option><option value="SALE">매출</option><option value="PURCHASE">매입</option><option value="REFUND">환불</option></select><select id="opsChannel"><option value="">채널 (전체)</option>${chs.map(x=>`<option>${esc(x.channel)}</option>`).join("")}</select></div><div class="ops-summary"><span>조회 결과 <b>${num(rows.length)}건</b></span><div><span>공급가액 <b>${won(sum(rows,"net_amount"))}</b></span><span>부가세 <b>${won(sum(rows,"vat_amount"))}</b></span><span class="total">합계 <b>${won(sum(rows,"total_amount"))}</b></span></div></div><div class="ops-table-wrap"><table class="ops-table"><thead><tr><th>일자</th><th>구분</th><th>채널</th><th>공급가액</th><th>부가세</th><th>합계</th><th>거래처/메뉴</th></tr></thead><tbody>${rows.length?rows.slice(0,100).map(x=>`<tr><td>${esc(x.business_date)}</td><td>${x.transaction_type==="SALE"?"매출":x.transaction_type==="PURCHASE"?"매입":esc(x.transaction_type)}</td><td>${esc(x.channel||"-")}</td><td>${won(x.net_amount)}</td><td>${won(x.vat_amount)}</td><td><b>${won(x.total_amount)}</b></td><td>${esc(x.counterparty||"-")}${x.is_demo?'<small class="ops-demo-mark">예시</small>':""}</td></tr>`).join(""):`<tr><td colspan="7">${empty("조회된 데이터가 없습니다.")}</td></tr>`}</tbody></table></div>`;opsType.onchange=async()=>{const rr=await BE.operationsInquiry(f,t,opsType.value||null,opsChannel.value||null);S.filtered=rr;drawInquiryRows(rr)};opsChannel.onchange=opsType.onchange}
else if(S.tab==="collect"){const rows=await BE.operationsImports();body.innerHTML=`<div class="ops-subhead"><b>데이터 수집</b><span>BizReport의 스크래핑 작업 흐름을 POS·배달·공급사 수집 큐로 확장했습니다.</span></div><div class="ops-source-grid">${[["KIS POS","매출·결제"],["배민","주문·정산"],["쿠팡이츠","주문·정산"],["땡겨요","주문·정산"],["온리원푸드넷","매입·입고"]].map(x=>`<div class="ops-source"><b>${x[0]}</b><small>${x[1]}</small><span class="ops-status">어댑터 준비</span></div>`).join("")}</div><div class="ops-card"><div class="ops-card-head"><b>수집 작업 이력</b><span class="ops-meta">${rows.length}건</span></div>${rows.length?rows.map(r=>`<div class="ops-row"><div class="ops-row-main"><b>${esc(r.source)}</b><small>${esc(r.file_name||"직접 수집")}</small></div><span class="ops-status ${r.status==="COMPLETED"?"ok":""}">${esc(r.status)}</span></div>`).join(""):empty("등록된 수집 작업이 없습니다.")}</div>`}
else if(S.tab==="upload"){const rows=await BE.operationsImports();body.innerHTML=`<div class="ops-subhead"><b>파일 업로드</b><span>BizReport의 카드 CSV 업로드 UX를 원천별 표준 업로드로 확장합니다.</span></div><div class="ops-upload-box"><label>데이터 원천<select disabled><option>CSV/XLSX — 실제 컬럼 매핑 준비 중</option></select></label><label>대상 파일<input type="file" accept=".csv,.xlsx,.xls" disabled></label><div class="ops-upload-actions"><button class="btn btn-secondary" disabled>표준서식 받기</button><button class="btn btn-primary" disabled>검증 후 업로드</button></div><small>실제 KIS/배민/공급사 파일을 받으면 컬럼 매핑을 확정한 뒤 활성화합니다. 임의 형식으로 운영 데이터를 변환하지 않습니다.</small></div><div class="ops-card"><b>업로드 대기열</b>${rows.length?rows.map(r=>`<div class="ops-row"><span>${esc(r.file_name||r.source)}</span><span class="ops-status">${esc(r.status)}</span></div>`).join(""):empty("등록된 업로드 기록이 없습니다.")}</div>`}
else if(S.tab==="inventory"){const rows=await BE.inventoryOverview();const catOf=r=>r.category||r.category_name||(/원두|우유|시럽|파우더|소스|티|차|과일|크림/.test(r.name||"")?"식재료":/컵|뚜껑|빨대|냅킨|포장/.test(r.name||"")?"포장·소모품":"기타"),cats=["전체",...new Set(rows.map(catOf))],renderInv=cat=>{const list=cat==="전체"?rows:rows.filter(r=>catOf(r)===cat),low=list.filter(r=>r.low_stock),value=list.reduce((n,r)=>n+Number(r.inventory_value||0),0);body.innerHTML='<div class="ops-inventory-toolbar"><label>카테고리<select id="opsInventoryCat">'+cats.map(x=>'<option '+(x===cat?"selected":"")+'>'+esc(x)+'</option>').join("")+'</select></label></div><div class="ops-kpis"><div class="ops-kpi primary"><span>현재 재고가치</span><b>'+won(value)+'</b></div><div class="ops-kpi"><span>발주 필요</span><b>'+low.length+'개 품목</b></div></div><div class="ops-stock-chart">'+(list.length?list.map(r=>{const par=Number(r.reorder_level||0),on=Number(r.on_hand||0),pct=par>0?Math.min(100,Math.max(0,on/par*100)):100,order=Math.max(0,par-on);return '<div class="ops-stock-bar '+(r.low_stock?"low":"")+'"><div><b>'+esc(r.name)+'</b><span>'+num(on)+' / PAR '+num(par)+' '+esc(r.unit)+'</span></div><i><em style="width:'+pct+'%"></em></i><strong>'+(order>0?"권장 발주 "+num(order)+" "+esc(r.unit):"적정")+'</strong></div>'}).join(""):empty("등록된 재고 품목이 없습니다."))+'</div><div class="ops-note">권장 발주량은 현재 단계에서 PAR(적정재고) − 현재고 기준입니다. 판매·레시피 사용량이 충분히 쌓이면 예상 소진량과 입고 예정량까지 반영하도록 확장합니다.</div>';document.getElementById("opsInventoryCat").onchange=e=>renderInv(e.target.value)};renderInv("전체")}
else if(S.tab==="recipe"){const rows=await BE.recipeList(),catOf=r=>r.category||r.menu_category||(/라떼|커피|아메리카노|에스프레소/.test(r.menu_name||"")?"커피":/티|차|에이드|주스/.test(r.menu_name||"")?"음료":"기타"),cats=["전체",...new Set(rows.map(catOf))],renderRecipes=cat=>{const list=cat==="전체"?rows:rows.filter(r=>catOf(r)===cat);body.innerHTML='<div class="ops-recipe-toolbar"><label>메뉴 카테고리<select id="opsRecipeCat">'+cats.map(x=>'<option '+(x===cat?"selected":"")+'>'+esc(x)+'</option>').join("")+'</select></label><div><button class="btn btn-secondary btn-sm" id="opsRecipeBulk">일괄 등록</button><button class="btn btn-primary btn-sm" id="opsRecipeAdd">+ 수동 등록</button></div></div><div class="ops-note">메뉴별 레시피는 원재료·사용량·수율을 기준으로 관리하고, 매입단가가 연결되면 메뉴 원가와 원가율이 자동 갱신되는 구조로 확장합니다.</div>'+(list.length?list.map(r=>'<div class="ops-card"><div class="ops-card-head"><div><small class="ops-recipe-cat">'+esc(catOf(r))+'</small><b>'+esc(r.menu_name)+'</b></div><span class="ops-status">'+esc(r.effective_from)+'~'+esc(r.effective_to||"현재")+'</span></div>'+(r.components||[]).map(x=>'<div class="ops-row"><span>'+esc(x.item_name)+'</span><strong>'+num(x.quantity)+' '+esc(x.unit)+'</strong></div>').join("")+'</div>').join(""):empty("등록된 레시피가 없습니다."));document.getElementById("opsRecipeCat").onchange=e=>renderRecipes(e.target.value);document.getElementById("opsRecipeAdd").onclick=()=>openRecipeEntry("manual");document.getElementById("opsRecipeBulk").onclick=()=>openRecipeEntry("bulk")};renderRecipes("전체")}
else if(S.tab==="recon"){const rows=await BE.reconciliationIssues(f,t);body.innerHTML=`<div class="ops-note">POS ↔ 배달/결제, 매입 ↔ 입고 등 서로 다른 원천의 누락·금액차이·취소 불일치를 기록하는 대사 큐입니다.</div>`+(rows.length?rows.map(r=>`<div class="ops-card"><div class="ops-card-head"><b>${esc(r.issue_type)}</b><span class="ops-status ${r.status==="OPEN"?"warn":"ok"}">${esc(r.status)}</span></div><div class="ops-row"><div class="ops-row-main"><b>${esc(r.business_date)}</b><small>${esc(r.left_source||"-")} ↔ ${esc(r.right_source||"-")}</small></div><strong>${r.amount_difference==null?"-":won(r.amount_difference)}</strong></div></div>`).join(""):empty("등록된 대사 이상 항목이 없습니다.","연결된 원천이 없으면 검사 대상도 없습니다."))}
else{body.innerHTML=empty("화면을 불러올 수 없습니다.")}
if(S.tab==="dashboard"){renderTrendCharts(trendData);document.querySelectorAll(".ops-range button").forEach(b=>b.onclick=async()=>{S.trend=b.dataset.range;document.querySelectorAll(".ops-range button").forEach(x=>x.classList.toggle("on",x===b));renderTrendCharts(await BE.operationsTrend(S.trend))})}}catch(e){body.innerHTML=empty("불러오기 실패",e.message)}}
function openRecipeEntry(mode){const wrap=document.createElement("div");wrap.className="ops-modal";wrap.innerHTML='<div class="ops-modal-sheet"><div class="ops-modal-head"><b>'+(mode==="bulk"?"레시피 일괄 등록":"레시피 수동 등록")+'</b><button type="button" aria-label="닫기">×</button></div><div class="ops-modal-body">'+(mode==="bulk"?'<div class="ops-upload-box"><label>메뉴·레시피 파일<input type="file" accept=".csv,.xlsx,.xls"></label><small>권장 컬럼: 메뉴 카테고리, 메뉴명, 원재료명, 사용량, 단위, 수율. 업로드 후 검증 화면에서 재고 품목과 매칭합니다.</small><button class="btn btn-primary" disabled>검증 후 등록</button></div>':'<div class="ops-upload-box"><label>메뉴 카테고리<input placeholder="예: 커피"></label><label>메뉴명<input placeholder="예: 카페라떼"></label><label>원재료 구성<textarea rows="6" placeholder="에스프레소 원두 18 g&#10;우유 220 ml"></textarea></label><small>현재 DB는 버전형 BOM 조회 구조까지 구축되어 있습니다. 편집 저장 API를 연결한 뒤 등록 버튼을 활성화합니다.</small><button class="btn btn-primary" disabled>레시피 등록</button></div>')+'</div></div>';document.body.appendChild(wrap);wrap.querySelector(".ops-modal-head button").onclick=()=>wrap.remove();wrap.onclick=e=>{if(e.target===wrap)wrap.remove()}}
function renderTrendCharts(tr){
 const totals=tr&&tr.totals||[],menus=tr&&tr.menus||[],names=tr&&tr.menu_names||[];
 const label=x=>{const d=new Date(x);if(S.trend==="1h")return String(d.getMinutes()).padStart(2,"0")+"분";if(S.trend==="24h")return String(d.getHours()).padStart(2,"0")+"시";if(S.trend==="1y")return (d.getMonth()+1)+"월";return (d.getMonth()+1)+"/"+d.getDate()};
 function chart(el,series,mode="bar"){if(!el)return;if(!series.length||!series[0].values.length){el.innerHTML=empty("이 기간에 표시할 데이터가 없습니다.","예시 데이터는 최근 30일 기준입니다. 1달을 선택하거나 예시 데이터를 다시 채워보세요.");return}
  const W=640,H=250,L=38,R=8,T=12,B=42,count=series[0].values.length,max=Math.max(1,...series.flatMap(s=>s.values.map(v=>Number(v.v||0)))),plotW=W-L-R,plotH=H-T-B,group=plotW/count,gap=Math.max(1,Math.min(4,group*.08)),barW=Math.max(1,(group-gap*2)/Math.max(1,series.length));
  const y=v=>T+plotH-(Number(v||0)/max)*plotH;
  const grid=[0,.25,.5,.75,1].map(k=>'<line x1="'+L+'" x2="'+(W-R)+'" y1="'+y(max*k)+'" y2="'+y(max*k)+'"/>').join("");
  const marks=mode==="line"?series.map((s,si)=>{const pts=s.values.map((v,i)=>(L+i*group+group/2).toFixed(1)+","+y(v.v).toFixed(1)).join(" ");const dots=s.values.map((v,i)=>{const val=Number(v.v||0),x=L+i*group+group/2,yy=y(val);return '<circle tabindex="0" role="button" data-series="'+esc(s.name)+'" data-label="'+esc(label(v.x))+'" data-value="'+val+'" class="s'+(si%8)+' ops-chart-point" cx="'+x.toFixed(1)+'" cy="'+yy.toFixed(1)+'" r="3"/>'}).join("");return '<polyline class="s'+(si%8)+'" points="'+pts+'"/>'+dots}).join(""):series.map((s,si)=>s.values.map((v,i)=>{const val=Number(v.v||0),x=L+i*group+gap+si*barW,yy=y(val),hh=Math.max(0,T+plotH-yy);return '<rect tabindex="0" role="button" data-series="'+esc(s.name)+'" data-label="'+esc(label(v.x))+'" data-value="'+val+'" class="s'+(si%8)+'" x="'+x.toFixed(1)+'" y="'+yy.toFixed(1)+'" width="'+Math.max(1,barW-1).toFixed(1)+'" height="'+hh.toFixed(1)+'" rx="2"/>'}).join("")).join("");
  const step=Math.max(1,Math.ceil(count/6)),guideIdx=series[0].values.map((_,i)=>i).filter(i=>i%step===0),vGuides=guideIdx.map(i=>{const gx=(L+i*group+group/2).toFixed(1);return '<line class="ops-chart-vguide" x1="'+gx+'" x2="'+gx+'" y1="'+T+'" y2="'+(T+plotH)+'"/>'}).join(""),labs=series[0].values.map((v,i)=>i%step===0?'<text x="'+(L+i*group+group/2).toFixed(1)+'" y="'+(H-13)+'">'+label(v.x)+'</text>':"").join("");
  el.innerHTML='<div class="ops-chart-stage"><svg viewBox="0 0 '+W+' '+H+'" role="img">'+grid+vGuides+marks+labs+'</svg><div class="ops-chart-tip" hidden></div></div><div class="ops-legend">'+series.map((s,i)=>'<span><i class="s'+(i%8)+'"></i>'+esc(s.name)+'</span>').join("")+'</div>';const tip=el.querySelector('.ops-chart-tip'),stage=el.querySelector('.ops-chart-stage');let selected=null;const show=(r)=>{selected=r;tip.innerHTML='<b>'+esc(r.dataset.series)+'</b><span>'+esc(r.dataset.label)+'</span><strong>'+won(r.dataset.value)+'</strong>';tip.hidden=false;const rb=r.getBoundingClientRect(),sb=stage.getBoundingClientRect();tip.style.left=Math.max(8,Math.min(sb.width-tip.offsetWidth-8,rb.left-sb.left+rb.width/2-tip.offsetWidth/2))+'px';tip.style.top=Math.max(8,rb.top-sb.top-tip.offsetHeight-8)+'px'},hide=()=>{selected=null;tip.hidden=true};el.querySelectorAll('[data-series]').forEach(r=>{r.addEventListener('pointerdown',e=>{show(r);if(e.pointerType!=='mouse')e.stopPropagation()},{passive:true});r.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse')show(r)});r.addEventListener('pointerleave',e=>{if(e.pointerType==='mouse'&&selected===r)hide()});r.addEventListener('focus',()=>show(r));r.addEventListener('click',e=>{e.stopPropagation();show(r)})});stage.addEventListener('pointerdown',e=>{if(!e.target.closest('[data-series]'))hide()},{passive:true})
 }
 chart(document.getElementById("opsTotalChart"),[{name:"총매출",values:totals.map(x=>({x:x.bucket,v:x.sales}))},{name:"총매입",values:totals.map(x=>({x:x.bucket,v:x.purchases}))}]);
 chart(document.getElementById("opsMenuChart"),names.map(n=>({name:n,values:totals.map(t=>({x:t.bucket,v:(menus.find(m=>m.bucket===t.bucket&&m.menu===n)||{}).amount||0}))})),"line");
}
function drawInquiryRows(rows){const tb=document.querySelector(".ops-table tbody");if(!tb)return;tb.innerHTML=rows.length?rows.slice(0,100).map(x=>`<tr><td>${esc(x.business_date)}</td><td>${x.transaction_type==="SALE"?"매출":x.transaction_type==="PURCHASE"?"매입":esc(x.transaction_type)}</td><td>${esc(x.channel||"-")}</td><td>${won(x.net_amount)}</td><td>${won(x.vat_amount)}</td><td><b>${won(x.total_amount)}</b></td><td>${esc(x.counterparty||"-")}${x.is_demo?'<small class="ops-demo-mark">예시</small>':""}</td></tr>`).join(""):`<tr><td colspan="7">${empty("조회된 데이터가 없습니다.")}</td></tr>`} window.renderOperations=shell})();
