/* Official inventory and recipe reference views extracted from supplied store documents. */
(function(){
const originalRender=window.renderOperations,REF=window.OPERATIONS_REFERENCE_V208||{inventory:[],recipes:[]};
const esc=value=>window.safeHtml?window.safeHtml(value):String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]));
const icon=name=>/원두|커피/.test(name)?"☕":/우유|밀크|크림/.test(name)?"🥛":/시럽|소스|청|베이스/.test(name)?"🧴":/과일|딸기|망고|자몽|멜론|레몬|라임/.test(name)?"🍓":/컵|뚜껑|빨대|봉투|포장|용기/.test(name)?"🥤":/팝콘/.test(name)?"🍿":/빵|베이글|케이크|떡|슈/.test(name)?"🥐":"📦";
let inventoryCategory="전체",inventoryQuery="",recipeCategory="전체",recipeQuery="";

function shell(title,subtitle){const root=document.getElementById("view"),nav=root.querySelector(".admin-subtabs")?.outerHTML||"";root.innerHTML='<div class="ops-head"><div><h2>'+esc(title)+'</h2><p>'+esc(subtitle)+'</p></div></div><div id="opsBody"></div>';if(nav)root.insertAdjacentHTML("afterbegin",nav);return document.getElementById("opsBody")}
function inventoryCard(row){const life=row.shelf_life||{},expiry=[life.storage_after&&"개봉 후 "+life.storage_after,life.expiry_after&&"상미 "+life.expiry_after,life.after_portion&&"소분·해동 "+life.after_portion].filter(Boolean).join(" · ");return '<article class="ops-stock-bar ops-stock-reference"><div class="ops-stock-title"><span class="ops-inventory-thumb" aria-hidden="true">'+icon(row.name)+'</span><b>'+esc(row.name)+'</b></div><span class="ops-reference-badge">운영 기준</span><dl><div><dt>현재</dt><dd>'+esc(row.current_text||"-")+'</dd></div><div><dt>최소</dt><dd>'+esc(row.minimum_text||"-")+'</dd></div><div><dt>주문</dt><dd>'+esc(row.order_text||"-")+'</dd></div></dl>'+(row.note?'<p>'+esc(row.note)+'</p>':"")+(expiry?'<small class="ops-stock-expiry">'+esc(expiry)+'</small>':"")+'</article>'}
function renderInventory(){const body=shell("재고","인하대점 재고표의 최소수량·현재수량·주문수량 기준을 원문 형식으로 확인합니다."),all=REF.inventory||[],categories=["전체",...new Set(all.map(x=>x.category))];let rows=inventoryCategory==="전체"?all:all.filter(x=>x.category===inventoryCategory);if(inventoryQuery)rows=rows.filter(x=>[x.name,x.current_text,x.minimum_text,x.order_text,x.note].some(v=>String(v||"").toLowerCase().includes(inventoryQuery)));body.innerHTML='<div class="ops-reference-meta"><b>원본 재고 '+all.length+'개 품목</b><span>인하대점 운영표 기준</span><button type="button" class="btn btn-secondary btn-sm" id="opsNumericInventory">수량 직접 관리</button></div><div class="ops-inventory-toolbar ops-reference-toolbar"><label>검색<input id="opsReferenceInventorySearch" type="search" value="'+esc(inventoryQuery)+'" placeholder="품목명·현재고·발주기준"></label><label>카테고리<select id="opsReferenceInventoryCat">'+categories.map(x=>'<option '+(x===inventoryCategory?'selected':'')+'>'+esc(x)+'</option>').join("")+'</select></label></div><div class="ops-reference-count">'+esc(inventoryCategory)+' · '+rows.length+'개</div><div class="ops-stock-chart ops-stock-grid">'+(rows.length?rows.map(inventoryCard).join(""):'<div class="ops-empty"><b>검색 결과가 없습니다.</b></div>')+'</div>';const search=document.getElementById("opsReferenceInventorySearch");search.oninput=e=>{inventoryQuery=e.target.value.trim().toLowerCase();renderInventory();const next=document.getElementById("opsReferenceInventorySearch");next.focus();next.setSelectionRange(next.value.length,next.value.length)};document.getElementById("opsReferenceInventoryCat").onchange=e=>{inventoryCategory=e.target.value;renderInventory()};document.getElementById("opsNumericInventory").onclick=()=>originalRender("inventory")}

function sourceLabel(row){return row.source_version==="26.09.11"?"10레시피 패널 · 2026.09.11":"9레시피 패널 · 2026.08.21"}
function recipeCard(row,index){const first=row.variants[0],preview=String(first?.content||"").split("\n").filter(Boolean).slice(0,3);return '<button type="button" class="ops-card ops-reference-recipe" data-reference-recipe="'+index+'"><div class="ops-card-head"><div><small class="ops-recipe-cat">'+esc(row.category)+'</small><b>'+esc(row.menu_name)+'</b></div><span class="ops-reference-badge">'+row.variants.length+'종</span></div><div class="ops-recipe-variant-chips">'+row.variants.map(x=>'<span>'+esc(x.label)+'</span>').join("")+'</div><div class="ops-reference-preview">'+preview.map(x=>'<span>'+esc(x)+'</span>').join("")+'</div><small class="ops-reference-source">'+esc(sourceLabel(row))+' · '+row.source_page+'쪽</small></button>'}
function openRecipe(row){const wrap=document.createElement("div");wrap.className="ops-modal";wrap.innerHTML='<div class="ops-modal-sheet ops-reference-recipe-sheet"><div class="ops-modal-head"><div><b>'+esc(row.menu_name)+'</b><small>'+esc(row.category)+'</small></div><button type="button" aria-label="닫기">×</button></div><div class="ops-modal-body"><div class="ops-reference-source-line">'+esc(sourceLabel(row))+' · '+row.source_page+'쪽</div><div class="ops-recipe-variant-grid">'+row.variants.map(v=>'<section><h3>'+esc(v.label)+'</h3><div>'+esc(v.content).replace(/\n/g,"<br>")+'</div></section>').join("")+'</div></div></div>';document.body.appendChild(wrap);const close=()=>wrap.remove();wrap.querySelector(".ops-modal-head button").onclick=close;wrap.onclick=e=>{if(e.target===wrap)close()}}
function renderRecipes(){const body=shell("레시피","공식 패널의 용량·온도별 제조 순서와 푸드 조리·포장 기준을 그대로 확인합니다."),all=REF.recipes||[],categories=["전체",...new Set(all.map(x=>x.category))];let rows=recipeCategory==="전체"?all:all.filter(x=>x.category===recipeCategory);if(recipeQuery)rows=rows.filter(x=>[x.menu_name,x.category,...x.variants.map(v=>v.content)].some(v=>String(v||"").toLowerCase().includes(recipeQuery)));body.innerHTML='<div class="ops-reference-meta"><b>공식 레시피 '+all.length+'개</b><span>음료 9패널 · 푸드 10패널 최신 우선</span><button type="button" class="btn btn-secondary btn-sm" id="opsRecipeEditor">등록 레시피 관리</button></div><div class="ops-recipe-toolbar ops-reference-toolbar"><label>검색<input id="opsReferenceRecipeSearch" type="search" value="'+esc(recipeQuery)+'" placeholder="메뉴명·재료·조리법"></label><label>메뉴 카테고리<select id="opsReferenceRecipeCat">'+categories.map(x=>'<option '+(x===recipeCategory?'selected':'')+'>'+esc(x)+'</option>').join("")+'</select></label></div><div class="ops-reference-count">'+esc(recipeCategory)+' · '+rows.length+'개</div><div class="ops-reference-recipe-list">'+(rows.length?rows.map((row,index)=>recipeCard(row,index)).join(""):'<div class="ops-empty"><b>검색 결과가 없습니다.</b></div>')+'</div>';const search=document.getElementById("opsReferenceRecipeSearch");search.oninput=e=>{recipeQuery=e.target.value.trim().toLowerCase();renderRecipes();const next=document.getElementById("opsReferenceRecipeSearch");next.focus();next.setSelectionRange(next.value.length,next.value.length)};document.getElementById("opsReferenceRecipeCat").onchange=e=>{recipeCategory=e.target.value;renderRecipes()};document.getElementById("opsRecipeEditor").onclick=()=>originalRender("recipe");body.querySelectorAll("[data-reference-recipe]").forEach((button,index)=>button.onclick=()=>openRecipe(rows[index]))}

window.renderOperations=async tab=>tab==="inventory"?renderInventory():tab==="recipe"?renderRecipes():originalRender(tab);
document.addEventListener("click",event=>{const active=event.target?.id==="opsNumericInventory"?"inventory":event.target?.id==="opsRecipeEditor"?"recipe":"";if(!active)return;setTimeout(()=>{const root=document.getElementById("view");if(root&&!root.querySelector(".admin-subtabs")&&typeof window.adminSubnav==="function")root.insertAdjacentHTML("afterbegin",window.adminSubnav(active))},0)});
})();
