import fs from 'node:fs';
const js=fs.readFileSync('actual_attendance.js','utf8');
const html=fs.readFileSync('actual_attendance.html','utf8');
const need=(ok,msg)=>{if(!ok)throw new Error(msg)};
need(js.includes('refreshAuth()'),'actual attendance must own an auth refresh path');
need(js.includes('r.status===401||r.status===403'),'actual attendance must retry auth failures');
need(js.includes('/JWT|NOT_AUTHORIZED|invalid claim|expired/i'),'actual attendance must recognize invalid sessions');
need(js.includes("rpc('list_store_employees',{p_store_id:storeId})"),'employee RPC must restrict to current store');
need(js.includes("const data=await rpc('admin_store_events_with_corrections'"),'attendance RPC must restrict to current store');
need(html.includes('actual_attendance.js?v='),'runtime cache version must load implementation');
console.log('actual attendance auth refresh QA PASS');