import fs from 'node:fs';
import assert from 'node:assert/strict';
const h=fs.readFileSync('index.html','utf8');
assert(h.includes('const APP_VERSION="v0.71";'),'version must be v0.71');
assert(h.includes('#empGrid{grid-template-columns:repeat(auto-fill,minmax(200px,1fr));'),'POS desktop must auto-fill');
assert(h.includes('@media(max-width:430px){#empGrid{grid-template-columns:repeat(2,minmax(0,1fr));'),'POS mobile must be 2 columns');
assert(h.includes('.payroll-employee-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));'),'payroll desktop must auto-fill');
assert(h.includes('@media(max-width:430px){.payroll-employee-grid{grid-template-columns:repeat(2,minmax(0,1fr));'),'payroll mobile must be 2 columns');
assert(h.includes('#adList{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));'),'admin today desktop must auto-fill');
assert(h.includes('@media(max-width:430px){#adList{grid-template-columns:repeat(2,minmax(0,1fr));'),'admin today mobile must be 2 columns');
assert(h.includes('.employee-list-mask{padding:8px;display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));'),'employee management desktop must auto-fill');
assert(h.includes('@media(max-width:430px){.employee-list-mask{grid-template-columns:repeat(2,minmax(0,1fr));'),'employee management mobile must be 2 columns');
assert(h.includes('class="employee-manage-card"'),'employee management must use shared card family');
assert(h.includes('class="att-edit-icon" data-fix="${e.id}"'),'admin today edit action must stay icon-only');
console.log('employee card responsive unification v0.71: PASS');