import fs from 'node:fs';
import assert from 'node:assert/strict';
const index=fs.readFileSync('index.html','utf8');
const meeting=fs.readFileSync('meeting_ui_20260919_v1.js','utf8');
assert(!meeting.includes('MutationObserver'),'global MutationObserver must stay removed');
assert(index.includes('meeting_ui_20260919_v1.js?v=20260919c'),'freeze hotfix asset must use a new cache key');
assert(!index.includes('meeting_ui_20260919_v1.js?v=20260919a'),'known-freezing cached asset key must never be reused');
assert(!index.includes('width:100%;}\\\\n  #substitutionEntryV1'),'literal backslash-n must not remain in tab CSS');
const enh=(meeting.match(/setInterval\(enhance,2000\)/g)||[]).length;
assert.equal(enh,1,'enhance timer must be registered once in source');
assert(!/setInterval\(enhance,\s*[01]?\d{0,2}\)/.test(meeting),'enhance must not spin at sub-second cadence');
console.log('iPhone startup/freeze cache regression: PASS');
