import fs from 'node:fs';import assert from 'node:assert/strict';
const read=p=>fs.readFileSync(p,'utf8');let pass=0;const t=(n,f)=>{f();pass++;console.log('PASS',n)};
const hub=read('admin_hub.html'),month=read('monthly_schedule.html'),contract=read('employment_contracts_v3.js'),contractHtml=read('employment_contracts.html'),review=read('attendance_review.html'),css=read('employment_contracts.css'),mcss=read('monthly_schedule.css'),idx=read('index.html');
t('관리자 허브 핵심 업무 6개',()=>['오늘 근태','근무 스케줄','직원 관리','계약·급여조건','계약서 관리','근태 확인'].forEach(x=>assert(hub.includes(x))));
t('월간 스케줄 급여·계약 cross-link 제거',()=>assert(!month.includes('급여·계약')));
t('스케줄 일별/월간 같은 업무 view',()=>{assert(month.includes('일별'));assert(month.includes('월간'))});
t('계약·급여조건 독립 화면',()=>assert(contractHtml.includes('계약 · 급여조건')));
t('계약 기본 화면에서 결근 판정 제거',()=>{assert(!contract.includes('renderAbsence'));assert(!contractHtml.includes('결근 판정'))});
t('근태 확인에서 absence decision 접근',()=>{assert(review.includes('근태 확인'));assert(review.includes('UNEXCUSED'));assert(review.includes('NOT_UNEXCUSED'));assert(review.includes('NEEDS_REVIEW'))});
t('HOURLY/MONTHLY 전환',()=>{assert(contract.includes("data-pay=\"HOURLY\""));assert(contract.includes("data-pay=\"MONTHLY\""))});
t('BUSINESS/INSURANCE 전환',()=>{assert(contract.includes('BUSINESS_INCOME'));assert(contract.includes('FOUR_INSURANCE'))});
t('night enabled RATE FLAT',()=>{assert(contract.includes('nightEnabled'));assert(contract.includes("value=\"RATE\""));assert(contract.includes("value=\"FLAT\""))});
t('사업소득 퍼센트 표시 정규화',()=>{assert(contract.includes('function fmtPct'));assert(contract.includes('toFixed(4)'))});
t('고용·계약 이력 progressive disclosure',()=>{assert(contract.includes('<details class="card advanced"'));assert(contract.includes('고용·계약 이력'))});
t('개발 용어 UI 제거',()=>['created_at','is_active로','schedule=WORK','J1/J2','EmploymentPeriod','EmploymentContract'].forEach(x=>assert(!contract.includes(`>${x}`))));
t('모바일 form overflow 방어',()=>{assert(css.includes('max-width:100%'));assert(css.includes('min-width:0'));assert(css.includes('overflow-x:hidden'));assert(mcss.includes('overflow-x:hidden'))});
t('safe-area 유지',()=>{assert(css.includes('safe-area-inset-bottom'));assert(mcss.includes('safe-area-inset-bottom'))});
t('관리 탭 기본 진입은 허브로 redirect',()=>assert(idx.includes('admin_hub.html')));
t('legacy admin deep-link escape hatch',()=>assert(idx.includes('legacyAdmin')));
t('일별 스케줄 deep-link',()=>assert(idx.includes('openSchedule')));
console.log(`IA/UX V1 QA: ${pass} PASS`);