import fs from 'node:fs';
import assert from 'node:assert/strict';
const index=fs.readFileSync('index.html','utf8');
const contract=fs.readFileSync('payroll_contract_authority_v1.js','utf8');
const night=fs.readFileSync('payroll_night_allowance_v1.js','utf8');
const loader=fs.readFileSync('payroll_elapsed_weeks_v1.js','utf8');
assert.match(index,/async serverPayroll\(ym\)/);
assert.match(index,/mode:"payroll",ym,store_id:Number\(CURRENT_STORE_ID\|\|1\)/);
assert.match(index,/typeof BE\.serverPayroll==="function"/);
assert.match(index,/SERVER_PAYROLL_AUTH_REQUIRED/);
assert.match(contract,/typeof BE\.serverPayroll==="function"\)\{lastResult=R;return R;/);
assert.match(night,/typeof BE\.serverPayroll==="function"\)\{window\.__nightPayrollResult=R;return R;/);
assert.match(loader,/payroll_contract_authority_v1\.js\?v=20261009v0185/);
assert.match(loader,/payroll_night_allowance_v1\.js\?v=20261009v0185/);
assert.match(index,/if\(LIVE && Number\(CURRENT_STORE_ID\)===1\)return;/);
assert.match(index,/const APP_VERSION="v0\.186"/);
console.log('PASS pilot payroll uses authenticated server result; no double premiums or browser Sheet timer race');
