import assert from 'node:assert/strict';
import fs from 'node:fs';
const base=fs.readFileSync('supabase/migrations/20261010235500_store_scoped_payroll_base.sql','utf8');
const source=fs.readFileSync('supabase/migrations/20261010235510_store_payroll_source_weekly_scope.sql','utf8');
const close=fs.readFileSync('supabase/migrations/20261010235520_store_scoped_payroll_close_reopen.sql','utf8');
const admin=fs.readFileSync('supabase/migrations/20261010235530_store_payroll_admin_rpcs.sql','utf8');
const edge=fs.readFileSync('supabase/functions/server-sync-sheet/index.ts','utf8');
const app=fs.readFileSync('index.html','utf8');
assert.match(base,/PRIMARY KEY \(store_id,ym\)/);
assert.match(base,/payroll_snapshot ADD COLUMN IF NOT EXISTS store_id/);
assert.match(base,/payroll_snapshot_reopen_audit ADD COLUMN IF NOT EXISTS store_id/);
assert.match(base,/WHERE id=1 AND onboarding_status='STAGED'/);
assert.match(base,/UPDATE public\.stores SET onboarding_status='READY'/);
assert.match(source,/p\.ym=p_ym and p\.store_id=p_store_id/);
assert.match(source,/payroll-close:'\|\|p_store_id\|\|':'\|\|v_ym/);
assert.match(source,/WHERE store_id=p_store_id AND ym=v_ym AND status='CLOSED'/);
assert.match(close,/INSERT INTO public\.payroll_snapshot\(store_id,ym,employee_id/);
assert.match(close,/INSERT INTO public\.payroll_period\(store_id,ym,status,updated_by,updated_at\)/);
assert.match(close,/ON CONFLICT\(store_id,ym\) DO UPDATE/);
assert.match(close,/server_payroll_reopen_verified\(p_store_id bigint, p_ym text/);
assert.match(close,/DELETE FROM public\.payroll_snapshot WHERE store_id=p_store_id AND ym=p_ym/);
assert.match(close,/INSERT INTO public\.payroll_snapshot_reopen_audit\(store_id,ym/);
assert.match(admin,/NOT public\.can_manage_store\(p_store_id\)/);
assert.match(admin,/public\.admin_store_payroll_period\(p_store_id bigint,p_ym text\)/);
assert.match(admin,/public\.admin_store_set_period_weeks\(/);
assert.match(admin,/public\.admin_store_snapshot\(p_store_id bigint,p_ym text\)/);
assert.match(edge,/onboarding_status!=="READY"/);
assert.match(edge,/p_store_id:storeId,p_ym:ym,p_reason:reason,p_actor_id:actor\.userId/);
assert.match(edge,/STORE_SHEET_SYNC_NOT_CONFIGURED/);
assert.doesNotMatch(edge,/if\(storeId!==1\)throw new HttpError\(403,"STORE_NOT_ENABLED"\)/);
assert.match(app,/rpc\("admin_store_payroll_period",\{p_store_id:CURRENT_STORE_ID\|\|1,p_ym:ym\}/);
assert.match(app,/rpc\("admin_store_set_period_weeks",\{p_store_id:CURRENT_STORE_ID\|\|1,p_ym:ym,p_weeks:weeks\}/);
assert.match(app,/rpc\("admin_store_snapshot",\{p_store_id:CURRENT_STORE_ID\|\|1,p_ym:ym\}/);
console.log('PASS per-store payroll period, weekly decisions, snapshots, audited reopen and secure staging');
