import fs from 'node:fs';import assert from 'node:assert/strict';
const html=fs.readFileSync('index.html','utf8'),js=fs.readFileSync('operations_v1.js','utf8'),css=fs.readFileSync('operations_v1.css','utf8');
for(const route of ['report','admin','pay','hours','sales','inventory','recipe']) assert.ok(html.includes('"'+route+'"'));
for(const label of ['리포트','직원','급여','운영시간','매출·매입','재고','레시피']) assert.ok(html.includes(label));
assert.ok(!html.includes('>매장운영</a>'));
for(const tab of ['renderOperations("dashboard")','renderOperations("inquiry")','renderOperations("inventory")','renderOperations("recipe")']) assert.ok(html.includes(tab));
for(const text of ['데이터 수집','파일 업로드','권장 발주','메뉴 카테고리','일괄 등록','수동 등록']) assert.ok(js.includes(text));
assert.ok(js.includes('openOpsModal("collect")'));assert.ok(js.includes('openOpsModal("upload")'));
assert.ok(css.includes('.ops-stock-chart'));assert.ok(css.includes('.ops-modal'));assert.ok(css.includes('.admin-subtabs-wide'));
new Function(js);
for(const m of html.matchAll(/<script(?![^>]*\\bsrc=)[^>]*>([\\s\\S]*?)<\\/script>/gi)) new Function(m[1]);
console.log('operations v1.56 navigation/inventory/recipe: PASS');
