import fs from 'node:fs';import assert from 'node:assert/strict';
const mod=fs.readFileSync('payroll_contract_authority_v1.js','utf8');
const loader=fs.readFileSync('payroll_elapsed_weeks_v1.js','utf8');
let pass=0;const t=(n,f)=>{f();pass++;console.log('PASS',n)};
t('extension loads after inline app boot',()=>{assert(loader.includes("window.addEventListener('load'"));assert(loader.includes("s.src='payroll_contract_authority_v1.js'"))});
t('payroll reads authoritative employment bundle',()=>{assert(mod.includes("rpc('admin_employment_bundle'"));assert(mod.includes('c.hourly_wage'));assert(mod.includes('c.weekly_contracted_minutes'));assert(mod.includes('c.business_deduction_rate'))});
t('recurring duplicate monthly overrides are excluded from calculation',()=>{assert(mod.includes('function safeOverride'));assert(!/out\.wage_override/.test(mod));assert(!/out\.juhyu_hours_override/.test(mod));assert(!/out\.tax_rate_override/.test(mod));assert(mod.includes('juhyu_weeks_override'));assert(mod.includes('adjust_amount'))});
t('existing finalized payroll formula is reused',()=>{assert(mod.includes('calcPayroll(emp,row.hours,R.weeks,ov)'));assert(!mod.includes('wage*row.hours'))});
t('monthly and four-insurance semantics are not invented',()=>{assert(mod.includes('월급제 급여 계산정책 미확정'));assert(mod.includes('4대보험 공제 계산정책 미확정'))});
t('contract gaps and mid-month incompatible changes fail visibly instead of guessing',()=>{assert(mod.includes('계약기간 밖 실근무'));assert(mod.includes('월중 계약조건 변경'))});
t('legacy no-contract employees remain backward compatible with visible warning',()=>{assert(mod.includes("mode:'LEGACY'"));assert(mod.includes('기존 급여설정으로 임시 계산'))});
t('payroll duplicate edit entry is removed and month adjustment hides recurring contract fields',()=>{assert(mod.includes("card.querySelector('[data-edit]')?.remove()"));assert(mod.includes("['maWage','maJh','maTax']"))});
t('current payroll refreshes while visible',()=>{assert(mod.includes('setInterval(refresh,60000)'));assert(mod.includes("visibilitychange"))});
console.log(`Payroll contract authority V1 QA: ${pass} PASS`);
