import assert from 'node:assert/strict';
import fs from 'node:fs';
const s=fs.readFileSync('index.html','utf8');
const start=s.indexOf('async function renderPos(');
const end=s.indexOf('\n}',start);
assert.ok(start>=0&&end>start,'renderPos missing');
const body=s.slice(start,end);
assert.match(body,/await BE\.listEmployeesState\(\)/);
assert.match(body,/if\(!grid\.isConnected \|\| location\.hash!=="#pos"\)return/);
assert.match(body,/const count=document\.getElementById\("empCount"\)/);
assert.match(body,/if\(!count\)return/);
console.log('PASS stale POS requests cannot mutate a removed route');
