import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
const edge=read('edge_server_sync_sheet.ts'),app=read('index.html'),bridge=read('server_payroll_bridge_v1.js');
const cron=read('supabase/migrations/20261009122500_sheet_server_writer_cron.sql');
const schema=read('supabase/migrations/20261009120500_sheet_server_sync_leases.sql');
const source=read('supabase/migrations/20261009120000_sheet_server_payroll_source.sql');
const pages=read('.github/workflows/p0-pages-deploy.yml'),script=read('.github/workflows/apps-script-deploy.yml');
for(const token of ['sheet_server_payroll_source','sheet_autosync_claim','sheet_autosync_finish','sheet_autosync_token_valid','automaticCycle','googleWrite','column_resize_applied','createPayrollEngine','mode==="deployment"','createRemoteJWKSet','jwtVerify'])assert.ok(edge.includes(token),token);
for(const token of ['row level security','grant execute on function public.sheet_autosync_claim','grant execute on function public.sheet_autosync_finish','vault.create_secret','retry_after'])assert.ok(schema.toLowerCase().includes(token.toLowerCase()),token);
assert.match(cron,/cron\.schedule\(\s*'baekeok-sheet-server-writer'/);
assert.match(cron,/'\* \* \* \* \*'/);
assert.match(cron,/x-sheet-autosync-token/);
assert.match(source,/security invoker/i);
assert.match(source,/grant execute on function public.sheet_server_payroll_source\(bigint,text\) to service_role/);
assert.ok(!source.includes('delete from')&&!source.includes('update public.payroll_snapshot'),'server source should be read only');
assert.ok(app.includes('APP_VERSION="v0.183"'));
assert.ok(app.includes('functions/v1/server-sync-sheet'));
assert.ok(app.includes('async serverPayroll(ym)'));
assert.ok(bridge.includes('window.__setServerPayrollResult?.(result)'));
assert.ok(read('payroll_elapsed_weeks_v1.js').includes("append('server_payroll_bridge_v1.js"));
assert.ok(pages.includes('id: deployment\n        uses: actions/deploy-pages@v4'));\nassert.ok(pages.includes('uses: actions/checkout@v4\n      - name: Confirm production Sheet sync'));
assert.ok(script.includes('node tools/trigger_sheet_deploy_sync.mjs'));
assert.match(read('tools/trigger_sheet_deploy_sync.mjs'),/body\.written!==true/);
assert.match(read('tools/trigger_sheet_deploy_sync.mjs'),/body\.column_resize_applied!==true/);
console.log('PASS server monthly write auth, signed post-deploy replay, pipeline and no browser dependency contracts');
