import fs from 'node:fs';
import assert from 'node:assert/strict';
import vm from 'node:vm';
const html=fs.readFileSync('index.html','utf8');
const gas=fs.readFileSync('apps_script.gs','utf8');
const begin=html.indexOf('async function buildSheetSyncPayload(ym){');
assert(begin>=0);
const end=html.indexOf('function sheetCorrectionReason(',begin);
const payload=html.slice(begin,end);
assert.match(payload,/calculated\.rows\.filter\(rec=>String\(rec\.employee_name\|\|''\)\.trim\(\)\.toUpperCase\(\)!=='TEST'\)/);
assert.match(payload,/for\(const rec of R\.rows\)/);
const a=gas.indexOf('function _writeMonth(');
const b=gas.indexOf('  // Senior October workbook is the display contract.',a);
assert(a>=0&&b>a);
const snippet=gas.slice(a,b);
assert.match(snippet,/payroll=withoutTestEmployee\(payroll\)/);
assert.match(snippet,/attendance=withoutTestEmployee\(attendance\)/);
assert.match(snippet,/sessions=withoutTestEmployee\(sessions\)/);
const context={};vm.createContext(context);
vm.runInContext(snippet+'\nthis.filter=withoutTestEmployee;',context);
const input={header:['날짜','직원명'],rows:[['2026-10-09','TEST'],['2026-10-09','실제직원'],['2026-10-10',' test ']]};
assert.equal(context.filter(input).rows.length,1);
assert.equal(context.filter(input).rows[0][1],'실제직원');
assert.equal(input.rows.length,3);
console.log('PASS TEST exclusion at client payload and Apps Script sync boundary');
