import assert from "node:assert/strict";
import fs from "node:fs";
const html=fs.readFileSync("index.html","utf8");
const api=fs.readFileSync("supabase/functions/server-sync-sheet/index.ts","utf8");
const engine=fs.readFileSync("supabase/functions/server-sync-sheet/engine.mjs","utf8");
assert.match(html,/functions\/v1\/server-sync-sheet/,"manual sync must use server payroll");
assert.match(html,/mode:"sync",ym,store_id:Number\(CURRENT_STORE_ID\|\|1\),payload/);
assert.doesNotMatch(html,/functions\/v1\/sync-sheet/,"legacy client-trusting sheet path must not remain");
for(const mode of ['"cron"','"dryrun"','"deployment"','"payroll"','"parity"','"sync"']) assert.ok(api.includes(mode),mode);
assert.match(api,/SERVER_CLIENT_PARITY_MISMATCH/);
assert.match(api,/SHEET_COLUMN_RESIZE_NOT_CONFIRMED/);
assert.match(api,/SHEET_WRITE_LOCATION_UNCONFIRMED/);
assert.match(api,/sheet_autosync_claim/);
assert.match(api,/sheet_autosync_finish/);
assert.match(api,/sheet_server_payroll_source/);
assert.match(api,/createRemoteJWKSet/);
assert.match(api,/jwtVerify/);
for(const keyword of ['computeMonthPayroll','buildSheetSyncPayload','applyCorrections','pairEvents','break_provision_mode','night_allowance']) assert.ok(engine.includes(keyword),keyword);
assert.match(index,/const APP_VERSION="v0\.\d+"/);
console.log("PASS server-owned sheet source, manual parity gate and payroll engine wiring");
