import fs from 'node:fs';
import assert from 'node:assert/strict';
const app=fs.readFileSync('index.html','utf8');
const gas=fs.readFileSync('apps_script.gs','utf8');
assert.match(app,/function payableSeconds\(shift,mode\)/);
assert.match(app,/shift\.status!=="COMPLETE"/);
assert.match(app,/Math\.min\(1800,Math\.max\(0,sec-14400\)\)\+Math\.min\(1800,Math\.max\(0,sec-30600\)\)/);
assert.match(app,/payableSessions:items\.map\(x=>sheetDuration\(payableSeconds\(x,rec\.breakMode\)\)\)/);
assert.match(app,/"휴게 제공 여부","급여산정시간"\], rows:detailedAttendance/);
assert.match(gas,/get\('급여산정시간'\)\|\|'0:00'/);
assert.doesNotMatch(gas,/var deduct=provided|var bonus=provided/);
console.log('Sheet payable-time source contract: PASS');
