import fs from 'node:fs';
import assert from 'node:assert/strict';
import vm from 'node:vm';
const app=fs.readFileSync('index.html','utf8');
const ui=fs.readFileSync('employment_contracts_v3.js','utf8');
const gas=fs.readFileSync('apps_script.gs','utf8');
const sql=fs.readFileSync('supabase/migrations/20261009193000_three_way_contract_break_mode.sql','utf8');
assert.match(ui,/<select id="breakProvisionMode">/);
for(const v of ['PROVIDED','NOT_PROVIDED','IGNORED'])assert.match(ui,new RegExp('value="'+v+'"'));
assert.doesNotMatch(ui,/id="breakTimeProvided" type="checkbox"/);
assert.match(ui,/admin_contract_break_mode_set/);
assert.match(ui,/\|\|'NOT_PROVIDED'/);
assert.match(sql,/alter column break_provision_mode set default 'NOT_PROVIDED'/);
assert.match(sql,/when break_time_provided then 'PROVIDED' else 'NOT_PROVIDED'/);
assert.match(sql,/public\.can_manage_store\(p_store_id\)/);
assert.match(app,/admin_store_payroll_contracts_v4/);
assert.match(app,/breakMode==='NOT_PROVIDED'\?breakEligibleCount:0/);
assert.match(app,/breakMode!=='NOT_PROVIDED'\?0:eligibleBreakSessions/);
assert.match(app,/breakDeductSeconds=breakTimeProvided\?/);
assert.match(app,/rec\.breakMode==="IGNORED"\?"미고려"/);
assert.match(app,/payableSeconds\(x,rec\.breakMode\)/);
const begin=app.indexOf('function payableSeconds(shift,mode){');
const end=app.indexOf('\n  const detailLookup=',begin);
assert(begin>0&&end>begin);
const ctx={};vm.createContext(ctx);vm.runInContext(app.slice(begin,end),ctx);
const shift={status:'COMPLETE',sec:9*3600};
assert.equal(ctx.payableSeconds(shift,'PROVIDED'),8*3600);
assert.equal(ctx.payableSeconds(shift,'NOT_PROVIDED'),10*3600);
assert.equal(ctx.payableSeconds(shift,'IGNORED'),9*3600);
assert.equal(ctx.payableSeconds({status:'INCOMPLETE',sec:9*3600},'IGNORED'),0);
assert.match(gas,/getRange\(hr,1,1,s\.data\.header\.length\)\.setBackground\(headerGreen\)/);
assert.match(gas,/getRange\(dr\.first,1,dr\.count,s\.data\.header\.length\)\.setBackground\(white\)/);
console.log('PASS three-way break payroll, sheet sync labels and no extra table-end columns');
