import fs from 'node:fs';import assert from 'node:assert/strict';
const r=p=>fs.readFileSync(p,'utf8');let pass=0;const t=(n,f)=>{f();pass++;console.log('PASS',n)};
const idx=r('index.html'),ec=r('employment_contracts_v3.js'),dj=r('daily_schedule.js'),dc=r('daily_schedule.css'),mj=r('monthly_schedule.js'),mc=r('monthly_schedule.css');
t('pending alert targets existing pending cards, not generic review',()=>{assert(idx.includes('id="attendanceAlert" href="#admin"'));assert(idx.includes('reqs=await BE.pendingRequests()'));assert(idx.includes('sec.scrollIntoView'));assert(!idx.includes('id="attendanceAlert" href="attendance_review.html"'))});
t('pending count and cards share one reqs source',()=>{assert(idx.includes('확인할 근태 ${reqs.length}건'));assert(idx.includes('for(const r of reqs)'))});
t('contract duplicate disclosure removed',()=>{assert(!ec.includes('고용·계약 이력 열기'));assert(!ec.includes('<details class="card advanced"'));assert(ec.includes('<section class="card advanced" id="history"><h2>고용·계약 이력</h2>'))});
t('contract back context is explicit',()=>{assert(idx.includes('from=employees'));assert(idx.includes('from=admin'));assert(ec.includes("from==='employees'?'‹ 직원':'‹ 관리'"));assert(ec.includes('index.html?focus=employees#admin'))});
t('daily native time controls are wrapper-constrained',()=>{assert(dj.includes('class="time-field"><input class="start"'));assert(dc.includes('.time-field{min-width:0;width:100%;max-width:100%;overflow:hidden}'));assert(dc.includes('width:100%!important'))});
t('monthly native time controls use same wrapper constraint',()=>{assert((mj.match(/class="time-field"><input id=/g)||[]).length>=2);assert(mc.includes('.time-field{min-width:0;width:100%;max-width:100%;overflow:hidden}'));assert(mc.includes('width:100%!important'))});
t('navigator dividers are symmetric and browser-independent',()=>{for(const css of [dc,mc]){assert(css.includes('.period-nav .btn:first-child{border-right:1px solid var(--line)}'));assert(css.includes('.period-nav .btn:last-child{border-left:1px solid var(--line)}'))}});
t('stored dates render a saved state class',()=>{assert(mj.includes("S.original.has(rowKey(emp.id,d))?'saved':''"));assert(mc.includes('.calday.saved:not(.selected)'));assert(mc.includes('.daycell.saved:not(.selected)'))});
t('selected style has precedence over saved',()=>{assert(mc.indexOf('.calday.saved:not(.selected)')<mc.indexOf('.calday.selected{'));assert(mc.indexOf('.daycell.saved:not(.selected)')<mc.indexOf('.daycell.selected{'))});
t('monthly projected payload logic unchanged',()=>{assert(mj.includes('function wizardProjectedPayload()'));assert(mj.includes('function wizardPayload(){return wizardProjectedPayload()}'))});
t('daily Schedule RPC path unchanged',()=>{assert(dj.includes("rpc('admin_schedule_set'"));assert(dj.includes("rpc('admin_schedule_delete'"))});
t('punch core untouched by V1.1.2 surface files',()=>assert(idx.includes('touch-action:manipulation')));
console.log(`UX V1.1.2 QA: ${pass} PASS`);
