import assert from 'node:assert/strict';
import fs from 'node:fs';
const sql=fs.readFileSync('supabase/migrations/20261010233000_weekly_decision_append_only.sql','utf8');
const edge=fs.readFileSync('supabase/functions/server-sync-sheet/index.ts','utf8');
const html=fs.readFileSync('index.html','utf8');
assert.match(sql,/decision IN \('APPROVE','REJECT','REAPPROVE'\)/);
assert.match(sql,/p_decision='REJECT' AND p_approved_won<>0/);
assert.match(sql,/REAPPROVAL_REQUIRED/);
assert.match(sql,/INITIAL_APPROVAL_REQUIRED/);
assert.match(sql,/WEEK_NOT_CLOSED/);
assert.match(sql,/ym2:=to_char\(p_week_start\+6,'YYYY-MM'\)/);
assert.match(sql,/pg_advisory_xact_lock/);
assert.match(sql,/p.ym IN \(ym1,ym2\) AND p.status='CLOSED'/);
assert.match(sql,/PAYROLL_ALREADY_CLOSED/);
assert.match(sql,/FROM PUBLIC,anon,authenticated/);
assert.match(edge,/weekMonday.getTime\(\)<monthBegin-6\*86400000/);
assert.match(edge,/client\.rpc\("server_record_weekly_decision_verified"/);
assert.match(html,/decision:decision==="REJECT"\?"REJECT":undefined/);
assert.match(html,/weeklyRejectSave/);
assert.match(html,/submitWeeklyDecision\("REJECT"\)/);
assert.match(edge,/approval_id:data,decision/);
console.log('PASS immutable approve/reject/reapprove flow and cross-month close guard');
