(()=>{
  if(window.__baekeokTestUiV1)return;window.__baekeokTestUiV1=true;
  if(!window.BaekeokTest)return;
  const T=window.BaekeokTest;
  function visual(){
    let s=document.getElementById('testModeStyle');
    if(!s){s=document.createElement('style');s.id='testModeStyle';s.textContent=`body.test-mode::before{content:"";position:fixed;inset:0;z-index:9990;pointer-events:none;background:rgba(120,70,255,.09);box-shadow:inset 0 0 0 3px rgba(120,70,255,.45)}#testModeBanner{position:fixed;z-index:9997;left:50%;top:calc(env(safe-area-inset-top) + 7px);transform:translateX(-50%);background:#5b35d5;color:#fff;border-radius:999px;padding:5px 10px;font-size:.68rem;font-weight:800;pointer-events:none;white-space:nowrap}#testModeCorner{position:fixed;z-index:10020;right:max(8px,env(safe-area-inset-right));top:calc(env(safe-area-inset-top) + 6px);display:flex;align-items:center;gap:5px;height:30px;padding:3px 7px;border-radius:999px;background:rgba(255,255,255,.94);border:1px solid #cfd8d2;box-shadow:0 2px 10px rgba(0,0,0,.12);font-size:10px;font-weight:800;color:#59645d;user-select:none;-webkit-user-select:none}#testModeCorner.on{color:#5b35d5;border-color:rgba(91,53,213,.45);background:#f5f1ff}#testModeCorner .tm-track{position:relative;width:28px;height:16px;border-radius:999px;background:#b8c0bb;transition:.15s}#testModeCorner.on .tm-track{background:#6a45d8}#testModeCorner .tm-knob{position:absolute;width:12px;height:12px;left:2px;top:2px;border-radius:50%;background:#fff;box-shadow:0 1px 2px rgba(0,0,0,.25);transition:.15s}#testModeCorner.on .tm-knob{transform:translateX(12px)}.test-mode-card{margin:10px 0;padding:12px;border:1px solid rgba(120,70,255,.45);border-radius:14px;background:rgba(120,70,255,.06)}.test-mode-card .rowx{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.test-mode-card input{height:40px;border:1px solid var(--line);border-radius:10px;background:var(--panel2);color:var(--ink);padding:0 8px}`;document.head.appendChild(s)}
    const on=T.enabled();document.body.classList.toggle('test-mode',on);
    let b=document.getElementById('testModeBanner');if(on){if(!b){b=document.createElement('div');b.id='testModeBanner';document.body.appendChild(b)}b.textContent='TEST MODE · 운영 데이터 변경 안 함'}else b?.remove();
    let c=document.getElementById('testModeCorner');if(!c){c=document.createElement('button');c.type='button';c.id='testModeCorner';c.setAttribute('aria-label','테스트 모드 전환');c.innerHTML='<span class="tm-label"></span><span class="tm-track"><span class="tm-knob"></span></span>';document.body.appendChild(c);c.onclick=()=>{const S=T.get();S.enabled=!S.enabled;if(S.enabled&&!S.now)S.now=new Date().toISOString();T.set(S);visual();remount();window.dispatchEvent(new CustomEvent('baekeok:test-mode-change',{detail:{enabled:S.enabled}}))}}
    c.classList.toggle('on',on);c.querySelector('.tm-label').textContent=on?'TEST':'LIVE';c.setAttribute('aria-pressed',on?'true':'false');
  }
  function mount(){
    const host=document.querySelector('.admin-quick');if(!host)return false;
    const old=document.getElementById('testModeCard');if(old){if(old.parentElement===host)return true;old.remove()}
    const S=T.get(),d=kstNow(),p=n=>String(n).padStart(2,'0'),v=`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`;
    const c=document.createElement('div');c.id='testModeCard';c.className='test-mode-card';c.innerHTML=`<div class="rowx"><b>테스트 모드</b><span style="font-size:.8rem;color:var(--text-muted)">${S.enabled?'켜짐':'꺼짐'} · 우상단 토글로 전환</span>${S.enabled?`<input id="testNow" type="datetime-local" value="${v}"><button class="btn btn-secondary btn-sm" id="testMinus8">-8시간</button><button class="btn btn-secondary btn-sm" id="testMinus1">-1시간</button><button class="btn btn-secondary btn-sm" id="testPlus1">+1시간</button><button class="btn btn-secondary btn-sm" id="testPlus8">+8시간</button><button class="btn btn-danger btn-sm" id="testReset">초기화</button>`:''}</div>${S.enabled?'<div style="font-size:.7rem;color:var(--text-muted);margin-top:6px">날짜·시간 직접 입력 또는 ±1/±8시간 조정 · 테스트 PIN 0000 · 출퇴근/정정/급여는 sandbox 데이터만 사용합니다.</div>':''}`;host.prepend(c);
    if(S.enabled){const shift=ms=>{S.now=new Date(kstNow().getTime()+ms).toISOString();T.set(S);location.reload()};document.getElementById('testNow').onchange=e=>{const n=new Date(e.target.value);if(!isNaN(n)){S.now=n.toISOString();T.set(S);location.reload()}};document.getElementById('testMinus8').onclick=()=>shift(-28800000);document.getElementById('testMinus1').onclick=()=>shift(-3600000);document.getElementById('testPlus1').onclick=()=>shift(3600000);document.getElementById('testPlus8').onclick=()=>shift(28800000);document.getElementById('testReset').onclick=()=>{if(confirm('테스트 데이터만 초기화할까요?')){S.events=[];S.corrections=[];S.seq=1;T.set(S);location.reload()}}}
    return true;
  }
  function remount(){document.getElementById('testModeCard')?.remove();mount()}
  function sync(){visual();mount()}
  if(typeof renderAdmin==='function'){const base=renderAdmin;renderAdmin=async function(...a){const r=await base.apply(this,a);queueMicrotask(sync);return r}}
  const observer=new MutationObserver(()=>{if(!document.getElementById('testModeCard')&&document.querySelector('.admin-quick'))mount()});
  const boot=()=>{sync();observer.observe(document.body,{childList:true,subtree:true});setTimeout(sync,0);setTimeout(sync,250);setTimeout(sync,1000)};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();